/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador;

import org.xtext.dsl.generador.AbstractGeneradorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GeneradorRuntimeModule extends AbstractGeneradorRuntimeModule {
}
