/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ParafarmaciaGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ParafarmaciaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Parafarmacia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParafarmaciaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTituloKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTituloAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTituloSTRINGTerminalRuleCall_4_0 = (RuleCall)cTituloAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cDescripcionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDescripcionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_8_0 = (RuleCall)cDescripcionAssignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cAparienciaAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cAparienciaAparienciaParserRuleCall_10_0 = (RuleCall)cAparienciaAssignment_10.eContents().get(0);
		private final Keyword cPaginasKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cLeftCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cPaginasAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cPaginasPaginaParserRuleCall_13_0 = (RuleCall)cPaginasAssignment_13.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Parafarmacia:
		//	'Parafarmacia' '{'
		//	'Titulo' '=' titulo=STRING ';'
		//	'Descripcion' '=' descripcion=STRING ';'
		//	apariencia=Apariencia
		//	'Paginas' '{' paginas+=Pagina* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Parafarmacia' '{' 'Titulo' '=' titulo=STRING ';' 'Descripcion' '=' descripcion=STRING ';' apariencia=Apariencia
		//'Paginas' '{' paginas+=Pagina* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Parafarmacia'
		public Keyword getParafarmaciaKeyword_0() { return cParafarmaciaKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'Titulo'
		public Keyword getTituloKeyword_2() { return cTituloKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//titulo=STRING
		public Assignment getTituloAssignment_4() { return cTituloAssignment_4; }
		
		//STRING
		public RuleCall getTituloSTRINGTerminalRuleCall_4_0() { return cTituloSTRINGTerminalRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
		
		//'Descripcion'
		public Keyword getDescripcionKeyword_6() { return cDescripcionKeyword_6; }
		
		//'='
		public Keyword getEqualsSignKeyword_7() { return cEqualsSignKeyword_7; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_8() { return cDescripcionAssignment_8; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_8_0() { return cDescripcionSTRINGTerminalRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
		
		//apariencia=Apariencia
		public Assignment getAparienciaAssignment_10() { return cAparienciaAssignment_10; }
		
		//Apariencia
		public RuleCall getAparienciaAparienciaParserRuleCall_10_0() { return cAparienciaAparienciaParserRuleCall_10_0; }
		
		//'Paginas'
		public Keyword getPaginasKeyword_11() { return cPaginasKeyword_11; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12() { return cLeftCurlyBracketKeyword_12; }
		
		//paginas+=Pagina*
		public Assignment getPaginasAssignment_13() { return cPaginasAssignment_13; }
		
		//Pagina
		public RuleCall getPaginasPaginaParserRuleCall_13_0() { return cPaginasPaginaParserRuleCall_13_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class AparienciaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Apariencia");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFondoPrincipalKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cColorFondo1Assignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cColorFondo1ColorParserRuleCall_4_0 = (RuleCall)cColorFondo1Assignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cFondoSecundarioKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cColorFondo2Assignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cColorFondo2ColorParserRuleCall_8_0 = (RuleCall)cColorFondo2Assignment_8.eContents().get(0);
		private final Keyword cSemicolonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cTextoKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cEqualsSignKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cColorTextoAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cColorTextoColorParserRuleCall_12_0 = (RuleCall)cColorTextoAssignment_12.eContents().get(0);
		private final Keyword cSemicolonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cFuenteKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cLeftCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cTituloKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cLeftCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Keyword cSizeH1Keyword_19 = (Keyword)cGroup.eContents().get(19);
		private final Keyword cEqualsSignKeyword_20 = (Keyword)cGroup.eContents().get(20);
		private final Assignment cSizeFuenteH1Assignment_21 = (Assignment)cGroup.eContents().get(21);
		private final RuleCall cSizeFuenteH1INTTerminalRuleCall_21_0 = (RuleCall)cSizeFuenteH1Assignment_21.eContents().get(0);
		private final Keyword cPxKeyword_22 = (Keyword)cGroup.eContents().get(22);
		private final Keyword cSemicolonKeyword_23 = (Keyword)cGroup.eContents().get(23);
		private final Keyword cSizeH2Keyword_24 = (Keyword)cGroup.eContents().get(24);
		private final Keyword cEqualsSignKeyword_25 = (Keyword)cGroup.eContents().get(25);
		private final Assignment cSizeFuenteH2Assignment_26 = (Assignment)cGroup.eContents().get(26);
		private final RuleCall cSizeFuenteH2INTTerminalRuleCall_26_0 = (RuleCall)cSizeFuenteH2Assignment_26.eContents().get(0);
		private final Keyword cPxKeyword_27 = (Keyword)cGroup.eContents().get(27);
		private final Keyword cSemicolonKeyword_28 = (Keyword)cGroup.eContents().get(28);
		private final Keyword cRightCurlyBracketKeyword_29 = (Keyword)cGroup.eContents().get(29);
		private final Keyword cCuerpoKeyword_30 = (Keyword)cGroup.eContents().get(30);
		private final Keyword cLeftCurlyBracketKeyword_31 = (Keyword)cGroup.eContents().get(31);
		private final Keyword cSizeKeyword_32 = (Keyword)cGroup.eContents().get(32);
		private final Keyword cEqualsSignKeyword_33 = (Keyword)cGroup.eContents().get(33);
		private final Assignment cSizeFuenteCuerpoAssignment_34 = (Assignment)cGroup.eContents().get(34);
		private final RuleCall cSizeFuenteCuerpoINTTerminalRuleCall_34_0 = (RuleCall)cSizeFuenteCuerpoAssignment_34.eContents().get(0);
		private final Keyword cPxKeyword_35 = (Keyword)cGroup.eContents().get(35);
		private final Keyword cSemicolonKeyword_36 = (Keyword)cGroup.eContents().get(36);
		private final Keyword cRightCurlyBracketKeyword_37 = (Keyword)cGroup.eContents().get(37);
		private final Keyword cRightCurlyBracketKeyword_38 = (Keyword)cGroup.eContents().get(38);
		
		//Apariencia:
		//	'Color' '{'
		//	'FondoPrincipal' '=' colorFondo1=Color ';'
		//	'FondoSecundario' '=' colorFondo2=Color ';'
		//	'Texto' '=' colorTexto=Color ';'
		//	'}'
		//	'Fuente' '{'
		//	'Titulo' '{'
		//	'SizeH1' '=' sizeFuenteH1=INT 'px' ';'
		//	'SizeH2' '=' sizeFuenteH2=INT 'px' ';'
		//	'}'
		//	'Cuerpo' '{'
		//	'Size' '=' sizeFuenteCuerpo=INT 'px' ';'
		//	'}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Color' '{' 'FondoPrincipal' '=' colorFondo1=Color ';' 'FondoSecundario' '=' colorFondo2=Color ';' 'Texto' '='
		//colorTexto=Color ';' '}' 'Fuente' '{' 'Titulo' '{' 'SizeH1' '=' sizeFuenteH1=INT 'px' ';' 'SizeH2' '='
		//sizeFuenteH2=INT 'px' ';' '}' 'Cuerpo' '{' 'Size' '=' sizeFuenteCuerpo=INT 'px' ';' '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Color'
		public Keyword getColorKeyword_0() { return cColorKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'FondoPrincipal'
		public Keyword getFondoPrincipalKeyword_2() { return cFondoPrincipalKeyword_2; }
		
		//'='
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }
		
		//colorFondo1=Color
		public Assignment getColorFondo1Assignment_4() { return cColorFondo1Assignment_4; }
		
		//Color
		public RuleCall getColorFondo1ColorParserRuleCall_4_0() { return cColorFondo1ColorParserRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
		
		//'FondoSecundario'
		public Keyword getFondoSecundarioKeyword_6() { return cFondoSecundarioKeyword_6; }
		
		//'='
		public Keyword getEqualsSignKeyword_7() { return cEqualsSignKeyword_7; }
		
		//colorFondo2=Color
		public Assignment getColorFondo2Assignment_8() { return cColorFondo2Assignment_8; }
		
		//Color
		public RuleCall getColorFondo2ColorParserRuleCall_8_0() { return cColorFondo2ColorParserRuleCall_8_0; }
		
		//';'
		public Keyword getSemicolonKeyword_9() { return cSemicolonKeyword_9; }
		
		//'Texto'
		public Keyword getTextoKeyword_10() { return cTextoKeyword_10; }
		
		//'='
		public Keyword getEqualsSignKeyword_11() { return cEqualsSignKeyword_11; }
		
		//colorTexto=Color
		public Assignment getColorTextoAssignment_12() { return cColorTextoAssignment_12; }
		
		//Color
		public RuleCall getColorTextoColorParserRuleCall_12_0() { return cColorTextoColorParserRuleCall_12_0; }
		
		//';'
		public Keyword getSemicolonKeyword_13() { return cSemicolonKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//'Fuente'
		public Keyword getFuenteKeyword_15() { return cFuenteKeyword_15; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_16() { return cLeftCurlyBracketKeyword_16; }
		
		//'Titulo'
		public Keyword getTituloKeyword_17() { return cTituloKeyword_17; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_18() { return cLeftCurlyBracketKeyword_18; }
		
		//'SizeH1'
		public Keyword getSizeH1Keyword_19() { return cSizeH1Keyword_19; }
		
		//'='
		public Keyword getEqualsSignKeyword_20() { return cEqualsSignKeyword_20; }
		
		//sizeFuenteH1=INT
		public Assignment getSizeFuenteH1Assignment_21() { return cSizeFuenteH1Assignment_21; }
		
		//INT
		public RuleCall getSizeFuenteH1INTTerminalRuleCall_21_0() { return cSizeFuenteH1INTTerminalRuleCall_21_0; }
		
		//'px'
		public Keyword getPxKeyword_22() { return cPxKeyword_22; }
		
		//';'
		public Keyword getSemicolonKeyword_23() { return cSemicolonKeyword_23; }
		
		//'SizeH2'
		public Keyword getSizeH2Keyword_24() { return cSizeH2Keyword_24; }
		
		//'='
		public Keyword getEqualsSignKeyword_25() { return cEqualsSignKeyword_25; }
		
		//sizeFuenteH2=INT
		public Assignment getSizeFuenteH2Assignment_26() { return cSizeFuenteH2Assignment_26; }
		
		//INT
		public RuleCall getSizeFuenteH2INTTerminalRuleCall_26_0() { return cSizeFuenteH2INTTerminalRuleCall_26_0; }
		
		//'px'
		public Keyword getPxKeyword_27() { return cPxKeyword_27; }
		
		//';'
		public Keyword getSemicolonKeyword_28() { return cSemicolonKeyword_28; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_29() { return cRightCurlyBracketKeyword_29; }
		
		//'Cuerpo'
		public Keyword getCuerpoKeyword_30() { return cCuerpoKeyword_30; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_31() { return cLeftCurlyBracketKeyword_31; }
		
		//'Size'
		public Keyword getSizeKeyword_32() { return cSizeKeyword_32; }
		
		//'='
		public Keyword getEqualsSignKeyword_33() { return cEqualsSignKeyword_33; }
		
		//sizeFuenteCuerpo=INT
		public Assignment getSizeFuenteCuerpoAssignment_34() { return cSizeFuenteCuerpoAssignment_34; }
		
		//INT
		public RuleCall getSizeFuenteCuerpoINTTerminalRuleCall_34_0() { return cSizeFuenteCuerpoINTTerminalRuleCall_34_0; }
		
		//'px'
		public Keyword getPxKeyword_35() { return cPxKeyword_35; }
		
		//';'
		public Keyword getSemicolonKeyword_36() { return cSemicolonKeyword_36; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_37() { return cRightCurlyBracketKeyword_37; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_38() { return cRightCurlyBracketKeyword_38; }
	}
	public class PaginaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Pagina");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPaginaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTituloKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTituloAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTituloSTRINGTerminalRuleCall_4_0 = (RuleCall)cTituloAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cCuerpoKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cCuerpoAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCuerpoCuerpoParserRuleCall_8_0 = (RuleCall)cCuerpoAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Pagina:
		//	'Pagina' name=ID ';'
		//	'Titulo' titulo=STRING ';'
		//	'Cuerpo' '{'
		//	cuerpo=Cuerpo
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Pagina' name=ID ';' 'Titulo' titulo=STRING ';' 'Cuerpo' '{' cuerpo=Cuerpo '}'
		public Group getGroup() { return cGroup; }
		
		//'Pagina'
		public Keyword getPaginaKeyword_0() { return cPaginaKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
		
		//'Titulo'
		public Keyword getTituloKeyword_3() { return cTituloKeyword_3; }
		
		//titulo=STRING
		public Assignment getTituloAssignment_4() { return cTituloAssignment_4; }
		
		//STRING
		public RuleCall getTituloSTRINGTerminalRuleCall_4_0() { return cTituloSTRINGTerminalRuleCall_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
		
		//'Cuerpo'
		public Keyword getCuerpoKeyword_6() { return cCuerpoKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//cuerpo=Cuerpo
		public Assignment getCuerpoAssignment_8() { return cCuerpoAssignment_8; }
		
		//Cuerpo
		public RuleCall getCuerpoCuerpoParserRuleCall_8_0() { return cCuerpoCuerpoParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class CuerpoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Cuerpo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cTextoAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cTextoSTRINGTerminalRuleCall_0_0_0 = (RuleCall)cTextoAssignment_0_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cProductosAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cProductosProductoParserRuleCall_1_0 = (RuleCall)cProductosAssignment_1.eContents().get(0);
		
		//Cuerpo:
		//	texto=STRING ';' | productos+=Producto*;
		@Override public ParserRule getRule() { return rule; }
		
		//texto=STRING ';' | productos+=Producto*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//texto=STRING ';'
		public Group getGroup_0() { return cGroup_0; }
		
		//texto=STRING
		public Assignment getTextoAssignment_0_0() { return cTextoAssignment_0_0; }
		
		//STRING
		public RuleCall getTextoSTRINGTerminalRuleCall_0_0_0() { return cTextoSTRINGTerminalRuleCall_0_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_0_1() { return cSemicolonKeyword_0_1; }
		
		//productos+=Producto*
		public Assignment getProductosAssignment_1() { return cProductosAssignment_1; }
		
		//Producto
		public RuleCall getProductosProductoParserRuleCall_1_0() { return cProductosProductoParserRuleCall_1_0; }
	}
	public class ProductoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Producto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cNombreAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNombreSTRINGTerminalRuleCall_2_0 = (RuleCall)cNombreAssignment_2.eContents().get(0);
		private final Assignment cPrecioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrecioPrecioParserRuleCall_3_0 = (RuleCall)cPrecioAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cImagenKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cImagenAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cImagenSTRINGTerminalRuleCall_4_1_0 = (RuleCall)cImagenAssignment_4_1.eContents().get(0);
		private final Assignment cConrecetaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cConrecetaConRecetaKeyword_5_0 = (Keyword)cConrecetaAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescripcionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescripcionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescripcionSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cDescripcionAssignment_6_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Producto:
		//	'Producto' name=ID nombre=STRING precio=Precio ('imagen' imagen=STRING)?
		//	conreceta?='con receta'? ('descripcion' descripcion=STRING)
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//'Producto' name=ID nombre=STRING precio=Precio ('imagen' imagen=STRING)? conreceta?='con receta'? ('descripcion'
		//descripcion=STRING) ';'
		public Group getGroup() { return cGroup; }
		
		//'Producto'
		public Keyword getProductoKeyword_0() { return cProductoKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//nombre=STRING
		public Assignment getNombreAssignment_2() { return cNombreAssignment_2; }
		
		//STRING
		public RuleCall getNombreSTRINGTerminalRuleCall_2_0() { return cNombreSTRINGTerminalRuleCall_2_0; }
		
		//precio=Precio
		public Assignment getPrecioAssignment_3() { return cPrecioAssignment_3; }
		
		//Precio
		public RuleCall getPrecioPrecioParserRuleCall_3_0() { return cPrecioPrecioParserRuleCall_3_0; }
		
		//('imagen' imagen=STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'imagen'
		public Keyword getImagenKeyword_4_0() { return cImagenKeyword_4_0; }
		
		//imagen=STRING
		public Assignment getImagenAssignment_4_1() { return cImagenAssignment_4_1; }
		
		//STRING
		public RuleCall getImagenSTRINGTerminalRuleCall_4_1_0() { return cImagenSTRINGTerminalRuleCall_4_1_0; }
		
		//conreceta?='con receta'?
		public Assignment getConrecetaAssignment_5() { return cConrecetaAssignment_5; }
		
		//'con receta'
		public Keyword getConrecetaConRecetaKeyword_5_0() { return cConrecetaConRecetaKeyword_5_0; }
		
		//'descripcion' descripcion=STRING
		public Group getGroup_6() { return cGroup_6; }
		
		//'descripcion'
		public Keyword getDescripcionKeyword_6_0() { return cDescripcionKeyword_6_0; }
		
		//descripcion=STRING
		public Assignment getDescripcionAssignment_6_1() { return cDescripcionAssignment_6_1; }
		
		//STRING
		public RuleCall getDescripcionSTRINGTerminalRuleCall_6_1_0() { return cDescripcionSTRINGTerminalRuleCall_6_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
	}
	public class PrecioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Precio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Precio:
		//	INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.dsl.parafarmacia.Parafarmacia.Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Color:
		//	'#' (ID | INT)+;
		@Override public ParserRule getRule() { return rule; }
		
		//'#' (ID | INT)+
		public Group getGroup() { return cGroup; }
		
		//'#'
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }
		
		//(ID | INT)+
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_0() { return cIDTerminalRuleCall_1_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_1() { return cINTTerminalRuleCall_1_1; }
	}
	
	
	private final ParafarmaciaElements pParafarmacia;
	private final AparienciaElements pApariencia;
	private final PaginaElements pPagina;
	private final CuerpoElements pCuerpo;
	private final ProductoElements pProducto;
	private final PrecioElements pPrecio;
	private final ColorElements pColor;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ParafarmaciaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pParafarmacia = new ParafarmaciaElements();
		this.pApariencia = new AparienciaElements();
		this.pPagina = new PaginaElements();
		this.pCuerpo = new CuerpoElements();
		this.pProducto = new ProductoElements();
		this.pPrecio = new PrecioElements();
		this.pColor = new ColorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.dsl.parafarmacia.Parafarmacia".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Parafarmacia:
	//	'Parafarmacia' '{'
	//	'Titulo' '=' titulo=STRING ';'
	//	'Descripcion' '=' descripcion=STRING ';'
	//	apariencia=Apariencia
	//	'Paginas' '{' paginas+=Pagina* '}'
	//	'}';
	public ParafarmaciaElements getParafarmaciaAccess() {
		return pParafarmacia;
	}
	
	public ParserRule getParafarmaciaRule() {
		return getParafarmaciaAccess().getRule();
	}
	
	//Apariencia:
	//	'Color' '{'
	//	'FondoPrincipal' '=' colorFondo1=Color ';'
	//	'FondoSecundario' '=' colorFondo2=Color ';'
	//	'Texto' '=' colorTexto=Color ';'
	//	'}'
	//	'Fuente' '{'
	//	'Titulo' '{'
	//	'SizeH1' '=' sizeFuenteH1=INT 'px' ';'
	//	'SizeH2' '=' sizeFuenteH2=INT 'px' ';'
	//	'}'
	//	'Cuerpo' '{'
	//	'Size' '=' sizeFuenteCuerpo=INT 'px' ';'
	//	'}'
	//	'}';
	public AparienciaElements getAparienciaAccess() {
		return pApariencia;
	}
	
	public ParserRule getAparienciaRule() {
		return getAparienciaAccess().getRule();
	}
	
	//Pagina:
	//	'Pagina' name=ID ';'
	//	'Titulo' titulo=STRING ';'
	//	'Cuerpo' '{'
	//	cuerpo=Cuerpo
	//	'}';
	public PaginaElements getPaginaAccess() {
		return pPagina;
	}
	
	public ParserRule getPaginaRule() {
		return getPaginaAccess().getRule();
	}
	
	//Cuerpo:
	//	texto=STRING ';' | productos+=Producto*;
	public CuerpoElements getCuerpoAccess() {
		return pCuerpo;
	}
	
	public ParserRule getCuerpoRule() {
		return getCuerpoAccess().getRule();
	}
	
	//Producto:
	//	'Producto' name=ID nombre=STRING precio=Precio ('imagen' imagen=STRING)?
	//	conreceta?='con receta'? ('descripcion' descripcion=STRING)
	//	';';
	public ProductoElements getProductoAccess() {
		return pProducto;
	}
	
	public ParserRule getProductoRule() {
		return getProductoAccess().getRule();
	}
	
	//Precio:
	//	INT '.' INT;
	public PrecioElements getPrecioAccess() {
		return pPrecio;
	}
	
	public ParserRule getPrecioRule() {
		return getPrecioAccess().getRule();
	}
	
	//Color:
	//	'#' (ID | INT)+;
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
