/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGeneradorScopeProvider extends DelegatingScopeProvider {
}
