/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ide;

import org.xtext.dsl.generador.ide.AbstractGeneradorIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GeneradorIdeModule extends AbstractGeneradorIdeModule {
}
