/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.dsl.generador.ide.contentassist.antlr.internal.InternalGeneradorParser;
import org.xtext.dsl.generador.services.GeneradorGrammarAccess;

public class GeneradorParser extends AbstractContentAssistParser {

	@Inject
	private GeneradorGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGeneradorParser createParser() {
		InternalGeneradorParser result = new InternalGeneradorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCategoriaAccess().getAlternatives(), "rule__Categoria__Alternatives");
					put(grammarAccess.getTipoAccess().getAlternatives(), "rule__Tipo__Alternatives");
					put(grammarAccess.getColorAccess().getAlternatives_1(), "rule__Color__Alternatives_1");
					put(grammarAccess.getMedidaAccess().getAlternatives(), "rule__Medida__Alternatives");
					put(grammarAccess.getParafarmaciaAccess().getGroup(), "rule__Parafarmacia__Group__0");
					put(grammarAccess.getAparienciaAccess().getGroup(), "rule__Apariencia__Group__0");
					put(grammarAccess.getProductoAccess().getGroup(), "rule__Producto__Group__0");
					put(grammarAccess.getPrecioAccess().getGroup(), "rule__Precio__Group__0");
					put(grammarAccess.getDesplegableAccess().getGroup(), "rule__Desplegable__Group__0");
					put(grammarAccess.getPermanenteAccess().getGroup(), "rule__Permanente__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getMedidaAccess().getGroup_0(), "rule__Medida__Group_0__0");
					put(grammarAccess.getMedidaAccess().getGroup_1(), "rule__Medida__Group_1__0");
					put(grammarAccess.getCorreoAccess().getGroup(), "rule__Correo__Group__0");
					put(grammarAccess.getRegistroAccess().getGroup(), "rule__Registro__Group__0");
					put(grammarAccess.getDireccionAccess().getGroup(), "rule__Direccion__Group__0");
					put(grammarAccess.getParafarmaciaAccess().getTituloAssignment_5(), "rule__Parafarmacia__TituloAssignment_5");
					put(grammarAccess.getParafarmaciaAccess().getFuenteAssignment_7(), "rule__Parafarmacia__FuenteAssignment_7");
					put(grammarAccess.getParafarmaciaAccess().getNombreAssignment_12(), "rule__Parafarmacia__NombreAssignment_12");
					put(grammarAccess.getParafarmaciaAccess().getDireccionAssignment_14(), "rule__Parafarmacia__DireccionAssignment_14");
					put(grammarAccess.getParafarmaciaAccess().getCifAssignment_16(), "rule__Parafarmacia__CifAssignment_16");
					put(grammarAccess.getParafarmaciaAccess().getRegistroAssignment_18(), "rule__Parafarmacia__RegistroAssignment_18");
					put(grammarAccess.getParafarmaciaAccess().getCorreoAssignment_20(), "rule__Parafarmacia__CorreoAssignment_20");
					put(grammarAccess.getParafarmaciaAccess().getTelefonoAssignment_22(), "rule__Parafarmacia__TelefonoAssignment_22");
					put(grammarAccess.getParafarmaciaAccess().getTipoAssignment_27(), "rule__Parafarmacia__TipoAssignment_27");
					put(grammarAccess.getParafarmaciaAccess().getAparienciaAssignment_32(), "rule__Parafarmacia__AparienciaAssignment_32");
					put(grammarAccess.getParafarmaciaAccess().getCategoriasAssignment_37(), "rule__Parafarmacia__CategoriasAssignment_37");
					put(grammarAccess.getParafarmaciaAccess().getNumProductosPorFilaAssignment_44(), "rule__Parafarmacia__NumProductosPorFilaAssignment_44");
					put(grammarAccess.getParafarmaciaAccess().getProductosAssignment_45(), "rule__Parafarmacia__ProductosAssignment_45");
					put(grammarAccess.getParafarmaciaAccess().getNombreUsuarioAssignment_50(), "rule__Parafarmacia__NombreUsuarioAssignment_50");
					put(grammarAccess.getParafarmaciaAccess().getEmailAssignment_52(), "rule__Parafarmacia__EmailAssignment_52");
					put(grammarAccess.getParafarmaciaAccess().getPasswordAssignment_54(), "rule__Parafarmacia__PasswordAssignment_54");
					put(grammarAccess.getAparienciaAccess().getPrincipalAssignment_5(), "rule__Apariencia__PrincipalAssignment_5");
					put(grammarAccess.getAparienciaAccess().getPrincipalClaroAssignment_9(), "rule__Apariencia__PrincipalClaroAssignment_9");
					put(grammarAccess.getAparienciaAccess().getSecundarioAssignment_13(), "rule__Apariencia__SecundarioAssignment_13");
					put(grammarAccess.getAparienciaAccess().getFondoAssignment_17(), "rule__Apariencia__FondoAssignment_17");
					put(grammarAccess.getAparienciaAccess().getFondoProductosAssignment_21(), "rule__Apariencia__FondoProductosAssignment_21");
					put(grammarAccess.getAparienciaAccess().getPreciosAssignment_25(), "rule__Apariencia__PreciosAssignment_25");
					put(grammarAccess.getAparienciaAccess().getTextoAssignment_29(), "rule__Apariencia__TextoAssignment_29");
					put(grammarAccess.getAparienciaAccess().getTituloColorAssignment_33(), "rule__Apariencia__TituloColorAssignment_33");
					put(grammarAccess.getAparienciaAccess().getNormalAssignment_40(), "rule__Apariencia__NormalAssignment_40");
					put(grammarAccess.getAparienciaAccess().getGrandeAssignment_44(), "rule__Apariencia__GrandeAssignment_44");
					put(grammarAccess.getAparienciaAccess().getTituloAssignment_48(), "rule__Apariencia__TituloAssignment_48");
					put(grammarAccess.getAparienciaAccess().getMenuAssignment_52(), "rule__Apariencia__MenuAssignment_52");
					put(grammarAccess.getAparienciaAccess().getLateralAssignment_57(), "rule__Apariencia__LateralAssignment_57");
					put(grammarAccess.getProductoAccess().getNombreProductoAssignment_3(), "rule__Producto__NombreProductoAssignment_3");
					put(grammarAccess.getProductoAccess().getDescripcionAssignment_5(), "rule__Producto__DescripcionAssignment_5");
					put(grammarAccess.getProductoAccess().getPrecioAssignment_7(), "rule__Producto__PrecioAssignment_7");
					put(grammarAccess.getProductoAccess().getCantidadAssignment_9(), "rule__Producto__CantidadAssignment_9");
					put(grammarAccess.getProductoAccess().getCategoriaAssignment_11(), "rule__Producto__CategoriaAssignment_11");
					put(grammarAccess.getTipoAccess().getDesplegableAssignment_0(), "rule__Tipo__DesplegableAssignment_0");
					put(grammarAccess.getTipoAccess().getPermanenteAssignment_1(), "rule__Tipo__PermanenteAssignment_1");
					put(grammarAccess.getDesplegableAccess().getColorAssignment_2(), "rule__Desplegable__ColorAssignment_2");
					put(grammarAccess.getPermanenteAccess().getColorAssignment_2(), "rule__Permanente__ColorAssignment_2");
					put(grammarAccess.getPermanenteAccess().getAlturaAssignment_4(), "rule__Permanente__AlturaAssignment_4");
					put(grammarAccess.getRegistroAccess().getTomoAssignment_3(), "rule__Registro__TomoAssignment_3");
					put(grammarAccess.getRegistroAccess().getFolioAssignment_5(), "rule__Registro__FolioAssignment_5");
					put(grammarAccess.getRegistroAccess().getSeccionAssignment_7(), "rule__Registro__SeccionAssignment_7");
					put(grammarAccess.getRegistroAccess().getHojaAssignment_9(), "rule__Registro__HojaAssignment_9");
					put(grammarAccess.getDireccionAccess().getCalleAssignment_3(), "rule__Direccion__CalleAssignment_3");
					put(grammarAccess.getDireccionAccess().getCiudadAssignment_5(), "rule__Direccion__CiudadAssignment_5");
					put(grammarAccess.getDireccionAccess().getPaisAssignment_7(), "rule__Direccion__PaisAssignment_7");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GeneradorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GeneradorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
