/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.dsl.generador.ide.contentassist.antlr.internal.InternalGeneradorParser;
import org.xtext.dsl.generador.services.GeneradorGrammarAccess;

public class GeneradorParser extends AbstractContentAssistParser {

	@Inject
	private GeneradorGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalGeneradorParser createParser() {
		InternalGeneradorParser result = new InternalGeneradorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCategoriaAccess().getAlternatives(), "rule__Categoria__Alternatives");
					put(grammarAccess.getTipoAccess().getAlternatives(), "rule__Tipo__Alternatives");
					put(grammarAccess.getColorAccess().getAlternatives_1(), "rule__Color__Alternatives_1");
					put(grammarAccess.getMedidaAccess().getAlternatives(), "rule__Medida__Alternatives");
					put(grammarAccess.getParafarmaciaAccess().getGroup(), "rule__Parafarmacia__Group__0");
					put(grammarAccess.getAparienciaAccess().getGroup(), "rule__Apariencia__Group__0");
					put(grammarAccess.getProductoAccess().getGroup(), "rule__Producto__Group__0");
					put(grammarAccess.getPrecioAccess().getGroup(), "rule__Precio__Group__0");
					put(grammarAccess.getDesplegableAccess().getGroup(), "rule__Desplegable__Group__0");
					put(grammarAccess.getPermanenteAccess().getGroup(), "rule__Permanente__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getMedidaAccess().getGroup_0(), "rule__Medida__Group_0__0");
					put(grammarAccess.getMedidaAccess().getGroup_1(), "rule__Medida__Group_1__0");
					put(grammarAccess.getCorreoAccess().getGroup(), "rule__Correo__Group__0");
					put(grammarAccess.getRegistroAccess().getGroup(), "rule__Registro__Group__0");
					put(grammarAccess.getDireccionAccess().getGroup(), "rule__Direccion__Group__0");
					put(grammarAccess.getParafarmaciaAccess().getTituloAssignment_5(), "rule__Parafarmacia__TituloAssignment_5");
					put(grammarAccess.getParafarmaciaAccess().getFuenteAssignment_7(), "rule__Parafarmacia__FuenteAssignment_7");
					put(grammarAccess.getParafarmaciaAccess().getNombreAssignment_12(), "rule__Parafarmacia__NombreAssignment_12");
					put(grammarAccess.getParafarmaciaAccess().getDireccionAssignment_14(), "rule__Parafarmacia__DireccionAssignment_14");
					put(grammarAccess.getParafarmaciaAccess().getCifAssignment_16(), "rule__Parafarmacia__CifAssignment_16");
					put(grammarAccess.getParafarmaciaAccess().getRegistroAssignment_18(), "rule__Parafarmacia__RegistroAssignment_18");
					put(grammarAccess.getParafarmaciaAccess().getCorreoAssignment_20(), "rule__Parafarmacia__CorreoAssignment_20");
					put(grammarAccess.getParafarmaciaAccess().getTelefonoAssignment_22(), "rule__Parafarmacia__TelefonoAssignment_22");
					put(grammarAccess.getParafarmaciaAccess().getTipoAssignment_27(), "rule__Parafarmacia__TipoAssignment_27");
					put(grammarAccess.getParafarmaciaAccess().getAparienciaAssignment_32(), "rule__Parafarmacia__AparienciaAssignment_32");
					put(grammarAccess.getParafarmaciaAccess().getCategoriasAssignment_37(), "rule__Parafarmacia__CategoriasAssignment_37");
					put(grammarAccess.getParafarmaciaAccess().getNumProductosPorFilaAssignment_42(), "rule__Parafarmacia__NumProductosPorFilaAssignment_42");
					put(grammarAccess.getParafarmaciaAccess().getProductosAssignment_43(), "rule__Parafarmacia__ProductosAssignment_43");
					put(grammarAccess.getParafarmaciaAccess().getNombreUsuarioAssignment_48(), "rule__Parafarmacia__NombreUsuarioAssignment_48");
					put(grammarAccess.getParafarmaciaAccess().getEmailAssignment_50(), "rule__Parafarmacia__EmailAssignment_50");
					put(grammarAccess.getParafarmaciaAccess().getPasswordAssignment_52(), "rule__Parafarmacia__PasswordAssignment_52");
					put(grammarAccess.getAparienciaAccess().getPrincipalAssignment_3(), "rule__Apariencia__PrincipalAssignment_3");
					put(grammarAccess.getAparienciaAccess().getPrincipalClaroAssignment_5(), "rule__Apariencia__PrincipalClaroAssignment_5");
					put(grammarAccess.getAparienciaAccess().getSecundarioAssignment_7(), "rule__Apariencia__SecundarioAssignment_7");
					put(grammarAccess.getAparienciaAccess().getFondoAssignment_9(), "rule__Apariencia__FondoAssignment_9");
					put(grammarAccess.getAparienciaAccess().getFondoProductosAssignment_11(), "rule__Apariencia__FondoProductosAssignment_11");
					put(grammarAccess.getAparienciaAccess().getPreciosAssignment_13(), "rule__Apariencia__PreciosAssignment_13");
					put(grammarAccess.getAparienciaAccess().getTextoAssignment_15(), "rule__Apariencia__TextoAssignment_15");
					put(grammarAccess.getAparienciaAccess().getTituloColorAssignment_17(), "rule__Apariencia__TituloColorAssignment_17");
					put(grammarAccess.getAparienciaAccess().getNormalAssignment_22(), "rule__Apariencia__NormalAssignment_22");
					put(grammarAccess.getAparienciaAccess().getGrandeAssignment_24(), "rule__Apariencia__GrandeAssignment_24");
					put(grammarAccess.getAparienciaAccess().getTituloAssignment_26(), "rule__Apariencia__TituloAssignment_26");
					put(grammarAccess.getAparienciaAccess().getMenuAssignment_28(), "rule__Apariencia__MenuAssignment_28");
					put(grammarAccess.getAparienciaAccess().getLateralAssignment_33(), "rule__Apariencia__LateralAssignment_33");
					put(grammarAccess.getProductoAccess().getNombreProductoAssignment_3(), "rule__Producto__NombreProductoAssignment_3");
					put(grammarAccess.getProductoAccess().getDescripcionAssignment_5(), "rule__Producto__DescripcionAssignment_5");
					put(grammarAccess.getProductoAccess().getPrecioAssignment_7(), "rule__Producto__PrecioAssignment_7");
					put(grammarAccess.getProductoAccess().getCantidadAssignment_9(), "rule__Producto__CantidadAssignment_9");
					put(grammarAccess.getProductoAccess().getCategoriaAssignment_11(), "rule__Producto__CategoriaAssignment_11");
					put(grammarAccess.getTipoAccess().getDesplegableAssignment_0(), "rule__Tipo__DesplegableAssignment_0");
					put(grammarAccess.getTipoAccess().getPermanenteAssignment_1(), "rule__Tipo__PermanenteAssignment_1");
					put(grammarAccess.getDesplegableAccess().getColorAssignment_2(), "rule__Desplegable__ColorAssignment_2");
					put(grammarAccess.getPermanenteAccess().getColorAssignment_2(), "rule__Permanente__ColorAssignment_2");
					put(grammarAccess.getPermanenteAccess().getAlturaAssignment_4(), "rule__Permanente__AlturaAssignment_4");
					put(grammarAccess.getRegistroAccess().getTomoAssignment_3(), "rule__Registro__TomoAssignment_3");
					put(grammarAccess.getRegistroAccess().getFolioAssignment_5(), "rule__Registro__FolioAssignment_5");
					put(grammarAccess.getRegistroAccess().getSeccionAssignment_7(), "rule__Registro__SeccionAssignment_7");
					put(grammarAccess.getRegistroAccess().getHojaAssignment_9(), "rule__Registro__HojaAssignment_9");
					put(grammarAccess.getDireccionAccess().getCalleAssignment_3(), "rule__Direccion__CalleAssignment_3");
					put(grammarAccess.getDireccionAccess().getCiudadAssignment_5(), "rule__Direccion__CiudadAssignment_5");
					put(grammarAccess.getDireccionAccess().getPaisAssignment_7(), "rule__Direccion__PaisAssignment_7");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GeneradorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GeneradorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
