/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.parafarmacia.parafarmacia.Apariencia;
import org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Apariencia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getColorFondo1 <em>Color Fondo1</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getColorFondo2 <em>Color Fondo2</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getColorTexto <em>Color Texto</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getSizeFuenteH1 <em>Size Fuente H1</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getSizeFuenteH2 <em>Size Fuente H2</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl#getSizeFuenteCuerpo <em>Size Fuente Cuerpo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AparienciaImpl extends MinimalEObjectImpl.Container implements Apariencia
{
  /**
   * The default value of the '{@link #getColorFondo1() <em>Color Fondo1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorFondo1()
   * @generated
   * @ordered
   */
  protected static final String COLOR_FONDO1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColorFondo1() <em>Color Fondo1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorFondo1()
   * @generated
   * @ordered
   */
  protected String colorFondo1 = COLOR_FONDO1_EDEFAULT;

  /**
   * The default value of the '{@link #getColorFondo2() <em>Color Fondo2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorFondo2()
   * @generated
   * @ordered
   */
  protected static final String COLOR_FONDO2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColorFondo2() <em>Color Fondo2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorFondo2()
   * @generated
   * @ordered
   */
  protected String colorFondo2 = COLOR_FONDO2_EDEFAULT;

  /**
   * The default value of the '{@link #getColorTexto() <em>Color Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorTexto()
   * @generated
   * @ordered
   */
  protected static final String COLOR_TEXTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColorTexto() <em>Color Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColorTexto()
   * @generated
   * @ordered
   */
  protected String colorTexto = COLOR_TEXTO_EDEFAULT;

  /**
   * The default value of the '{@link #getSizeFuenteH1() <em>Size Fuente H1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteH1()
   * @generated
   * @ordered
   */
  protected static final int SIZE_FUENTE_H1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeFuenteH1() <em>Size Fuente H1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteH1()
   * @generated
   * @ordered
   */
  protected int sizeFuenteH1 = SIZE_FUENTE_H1_EDEFAULT;

  /**
   * The default value of the '{@link #getSizeFuenteH2() <em>Size Fuente H2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteH2()
   * @generated
   * @ordered
   */
  protected static final int SIZE_FUENTE_H2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeFuenteH2() <em>Size Fuente H2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteH2()
   * @generated
   * @ordered
   */
  protected int sizeFuenteH2 = SIZE_FUENTE_H2_EDEFAULT;

  /**
   * The default value of the '{@link #getSizeFuenteCuerpo() <em>Size Fuente Cuerpo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteCuerpo()
   * @generated
   * @ordered
   */
  protected static final int SIZE_FUENTE_CUERPO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSizeFuenteCuerpo() <em>Size Fuente Cuerpo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSizeFuenteCuerpo()
   * @generated
   * @ordered
   */
  protected int sizeFuenteCuerpo = SIZE_FUENTE_CUERPO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AparienciaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ParafarmaciaPackage.Literals.APARIENCIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getColorFondo1()
  {
    return colorFondo1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColorFondo1(String newColorFondo1)
  {
    String oldColorFondo1 = colorFondo1;
    colorFondo1 = newColorFondo1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__COLOR_FONDO1, oldColorFondo1, colorFondo1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getColorFondo2()
  {
    return colorFondo2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColorFondo2(String newColorFondo2)
  {
    String oldColorFondo2 = colorFondo2;
    colorFondo2 = newColorFondo2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__COLOR_FONDO2, oldColorFondo2, colorFondo2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getColorTexto()
  {
    return colorTexto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setColorTexto(String newColorTexto)
  {
    String oldColorTexto = colorTexto;
    colorTexto = newColorTexto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__COLOR_TEXTO, oldColorTexto, colorTexto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSizeFuenteH1()
  {
    return sizeFuenteH1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSizeFuenteH1(int newSizeFuenteH1)
  {
    int oldSizeFuenteH1 = sizeFuenteH1;
    sizeFuenteH1 = newSizeFuenteH1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H1, oldSizeFuenteH1, sizeFuenteH1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSizeFuenteH2()
  {
    return sizeFuenteH2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSizeFuenteH2(int newSizeFuenteH2)
  {
    int oldSizeFuenteH2 = sizeFuenteH2;
    sizeFuenteH2 = newSizeFuenteH2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H2, oldSizeFuenteH2, sizeFuenteH2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSizeFuenteCuerpo()
  {
    return sizeFuenteCuerpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSizeFuenteCuerpo(int newSizeFuenteCuerpo)
  {
    int oldSizeFuenteCuerpo = sizeFuenteCuerpo;
    sizeFuenteCuerpo = newSizeFuenteCuerpo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_CUERPO, oldSizeFuenteCuerpo, sizeFuenteCuerpo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO1:
        return getColorFondo1();
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO2:
        return getColorFondo2();
      case ParafarmaciaPackage.APARIENCIA__COLOR_TEXTO:
        return getColorTexto();
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H1:
        return getSizeFuenteH1();
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H2:
        return getSizeFuenteH2();
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_CUERPO:
        return getSizeFuenteCuerpo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO1:
        setColorFondo1((String)newValue);
        return;
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO2:
        setColorFondo2((String)newValue);
        return;
      case ParafarmaciaPackage.APARIENCIA__COLOR_TEXTO:
        setColorTexto((String)newValue);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H1:
        setSizeFuenteH1((Integer)newValue);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H2:
        setSizeFuenteH2((Integer)newValue);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_CUERPO:
        setSizeFuenteCuerpo((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO1:
        setColorFondo1(COLOR_FONDO1_EDEFAULT);
        return;
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO2:
        setColorFondo2(COLOR_FONDO2_EDEFAULT);
        return;
      case ParafarmaciaPackage.APARIENCIA__COLOR_TEXTO:
        setColorTexto(COLOR_TEXTO_EDEFAULT);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H1:
        setSizeFuenteH1(SIZE_FUENTE_H1_EDEFAULT);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H2:
        setSizeFuenteH2(SIZE_FUENTE_H2_EDEFAULT);
        return;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_CUERPO:
        setSizeFuenteCuerpo(SIZE_FUENTE_CUERPO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO1:
        return COLOR_FONDO1_EDEFAULT == null ? colorFondo1 != null : !COLOR_FONDO1_EDEFAULT.equals(colorFondo1);
      case ParafarmaciaPackage.APARIENCIA__COLOR_FONDO2:
        return COLOR_FONDO2_EDEFAULT == null ? colorFondo2 != null : !COLOR_FONDO2_EDEFAULT.equals(colorFondo2);
      case ParafarmaciaPackage.APARIENCIA__COLOR_TEXTO:
        return COLOR_TEXTO_EDEFAULT == null ? colorTexto != null : !COLOR_TEXTO_EDEFAULT.equals(colorTexto);
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H1:
        return sizeFuenteH1 != SIZE_FUENTE_H1_EDEFAULT;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_H2:
        return sizeFuenteH2 != SIZE_FUENTE_H2_EDEFAULT;
      case ParafarmaciaPackage.APARIENCIA__SIZE_FUENTE_CUERPO:
        return sizeFuenteCuerpo != SIZE_FUENTE_CUERPO_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (colorFondo1: ");
    result.append(colorFondo1);
    result.append(", colorFondo2: ");
    result.append(colorFondo2);
    result.append(", colorTexto: ");
    result.append(colorTexto);
    result.append(", sizeFuenteH1: ");
    result.append(sizeFuenteH1);
    result.append(", sizeFuenteH2: ");
    result.append(sizeFuenteH2);
    result.append(", sizeFuenteCuerpo: ");
    result.append(sizeFuenteCuerpo);
    result.append(')');
    return result.toString();
  }

} //AparienciaImpl
