/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo;
import org.xtext.dsl.parafarmacia.parafarmacia.Pagina;
import org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pagina</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl#getCuerpo <em>Cuerpo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PaginaImpl extends MinimalEObjectImpl.Container implements Pagina
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected static final String TITULO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected String titulo = TITULO_EDEFAULT;

  /**
   * The cached value of the '{@link #getCuerpo() <em>Cuerpo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCuerpo()
   * @generated
   * @ordered
   */
  protected Cuerpo cuerpo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PaginaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ParafarmaciaPackage.Literals.PAGINA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.PAGINA__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitulo()
  {
    return titulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitulo(String newTitulo)
  {
    String oldTitulo = titulo;
    titulo = newTitulo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.PAGINA__TITULO, oldTitulo, titulo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Cuerpo getCuerpo()
  {
    return cuerpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCuerpo(Cuerpo newCuerpo, NotificationChain msgs)
  {
    Cuerpo oldCuerpo = cuerpo;
    cuerpo = newCuerpo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.PAGINA__CUERPO, oldCuerpo, newCuerpo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCuerpo(Cuerpo newCuerpo)
  {
    if (newCuerpo != cuerpo)
    {
      NotificationChain msgs = null;
      if (cuerpo != null)
        msgs = ((InternalEObject)cuerpo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ParafarmaciaPackage.PAGINA__CUERPO, null, msgs);
      if (newCuerpo != null)
        msgs = ((InternalEObject)newCuerpo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ParafarmaciaPackage.PAGINA__CUERPO, null, msgs);
      msgs = basicSetCuerpo(newCuerpo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ParafarmaciaPackage.PAGINA__CUERPO, newCuerpo, newCuerpo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.PAGINA__CUERPO:
        return basicSetCuerpo(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.PAGINA__NAME:
        return getName();
      case ParafarmaciaPackage.PAGINA__TITULO:
        return getTitulo();
      case ParafarmaciaPackage.PAGINA__CUERPO:
        return getCuerpo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.PAGINA__NAME:
        setName((String)newValue);
        return;
      case ParafarmaciaPackage.PAGINA__TITULO:
        setTitulo((String)newValue);
        return;
      case ParafarmaciaPackage.PAGINA__CUERPO:
        setCuerpo((Cuerpo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.PAGINA__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ParafarmaciaPackage.PAGINA__TITULO:
        setTitulo(TITULO_EDEFAULT);
        return;
      case ParafarmaciaPackage.PAGINA__CUERPO:
        setCuerpo((Cuerpo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ParafarmaciaPackage.PAGINA__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ParafarmaciaPackage.PAGINA__TITULO:
        return TITULO_EDEFAULT == null ? titulo != null : !TITULO_EDEFAULT.equals(titulo);
      case ParafarmaciaPackage.PAGINA__CUERPO:
        return cuerpo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", titulo: ");
    result.append(titulo);
    result.append(')');
    return result.toString();
  }

} //PaginaImpl
