/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.dsl.parafarmacia.parafarmacia.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ParafarmaciaFactoryImpl extends EFactoryImpl implements ParafarmaciaFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ParafarmaciaFactory init()
  {
    try
    {
      ParafarmaciaFactory theParafarmaciaFactory = (ParafarmaciaFactory)EPackage.Registry.INSTANCE.getEFactory(ParafarmaciaPackage.eNS_URI);
      if (theParafarmaciaFactory != null)
      {
        return theParafarmaciaFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ParafarmaciaFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParafarmaciaFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ParafarmaciaPackage.PARAFARMACIA: return createParafarmacia();
      case ParafarmaciaPackage.APARIENCIA: return createApariencia();
      case ParafarmaciaPackage.PAGINA: return createPagina();
      case ParafarmaciaPackage.CUERPO: return createCuerpo();
      case ParafarmaciaPackage.PRODUCTO: return createProducto();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parafarmacia createParafarmacia()
  {
    ParafarmaciaImpl parafarmacia = new ParafarmaciaImpl();
    return parafarmacia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Apariencia createApariencia()
  {
    AparienciaImpl apariencia = new AparienciaImpl();
    return apariencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Pagina createPagina()
  {
    PaginaImpl pagina = new PaginaImpl();
    return pagina;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Cuerpo createCuerpo()
  {
    CuerpoImpl cuerpo = new CuerpoImpl();
    return cuerpo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Producto createProducto()
  {
    ProductoImpl producto = new ProductoImpl();
    return producto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParafarmaciaPackage getParafarmaciaPackage()
  {
    return (ParafarmaciaPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ParafarmaciaPackage getPackage()
  {
    return ParafarmaciaPackage.eINSTANCE;
  }

} //ParafarmaciaFactoryImpl
