/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.dsl.generador.parser.antlr.internal.InternalGeneradorParser;
import org.xtext.dsl.generador.services.GeneradorGrammarAccess;

public class GeneradorParser extends AbstractAntlrParser {

	@Inject
	private GeneradorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGeneradorParser createParser(XtextTokenStream stream) {
		return new InternalGeneradorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Parafarmacia";
	}

	public GeneradorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GeneradorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
