/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia;

import org.xtext.dsl.parafarmacia.AbstractParafarmaciaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ParafarmaciaRuntimeModule extends AbstractParafarmaciaRuntimeModule {
}
