/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia;

import org.xtext.dsl.parafarmacia.ParafarmaciaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ParafarmaciaStandaloneSetup extends ParafarmaciaStandaloneSetupGenerated {
  public static void doSetup() {
    new ParafarmaciaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
