/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class GeneradorNewProjectWizard extends XtextNewProjectWizard {

	private GeneradorWizardNewProjectCreationPage mainPage;

	@Inject
	public GeneradorNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Generador Project");
	}

	protected GeneradorWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Generador Project");
		mainPage.setDescription("Create a new Generador project.");
		addPage(mainPage);
	}

	protected GeneradorWizardNewProjectCreationPage createMainPage(String pageName) {
		return new GeneradorWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		GeneradorProjectInfo projectInfo = new GeneradorProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
