/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.dsl.parafarmacia.validation.ParafarmaciaValidator;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class ParafarmaciaQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(ParafarmaciaValidator.INVALID_COLOR)
  public void arreglarColor(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      final String colorActual = xtextDocument.get((issue.getOffset()).intValue(), (issue.getLength()).intValue());
      xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), colorActual.substring(0, 7));
    };
    acceptor.accept(issue, "Arreglar color", "Se cambiará por el código de un color real", "producto.ico", _function);
  }
}
