/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class GeneradorWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public GeneradorWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
