/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ParafarmaciaWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractParafarmaciaWebModule extends DefaultWebModule {

}
