
package ws.parafarmacia.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IParafarmaciaWS", targetNamespace = "http://parafarmacia.business.ws.impl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IParafarmaciaWS {


    /**
     * 
     * @return
     *     returns java.util.List<ws.parafarmacia.webservice.Producto>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductos", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetProductos")
    @ResponseWrapper(localName = "getProductosResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetProductosResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getProductosRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getProductosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getProductos/Fault/Exception")
    })
    public List<Producto> getProductos()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Producto
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProducto", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdateProducto")
    @ResponseWrapper(localName = "updateProductoResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdateProductoResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateProductoRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateProducto/Fault/Exception")
    })
    public Producto updateProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        Producto arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Producto
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newProducto", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewProducto")
    @ResponseWrapper(localName = "newProductoResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewProductoResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newProductoRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newProducto/Fault/Exception")
    })
    public Producto newProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        Producto arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeProducto", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.RemoveProducto")
    @ResponseWrapper(localName = "removeProductoResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.RemoveProductoResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/removeProductoRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/removeProductoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/removeProducto/Fault/Exception")
    })
    public void removeProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.parafarmacia.webservice.Pedido>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPedidos", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetPedidos")
    @ResponseWrapper(localName = "getPedidosResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetPedidosResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getPedidosRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getPedidosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getPedidos/Fault/Exception")
    })
    public List<Pedido> getPedidos()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Pedido
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePedido", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdatePedido")
    @ResponseWrapper(localName = "updatePedidoResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdatePedidoResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updatePedidoRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updatePedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updatePedido/Fault/Exception")
    })
    public Pedido updatePedido(
        @WebParam(name = "arg0", targetNamespace = "")
        Pedido arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Pedido
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newPedido", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewPedido")
    @ResponseWrapper(localName = "newPedidoResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewPedidoResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newPedidoRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newPedidoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newPedido/Fault/Exception")
    })
    public Pedido newPedido(
        @WebParam(name = "arg0", targetNamespace = "")
        Pedido arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ws.parafarmacia.webservice.Usuario>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsuarios", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetUsuarios")
    @ResponseWrapper(localName = "getUsuariosResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.GetUsuariosResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getUsuariosRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getUsuariosResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/getUsuarios/Fault/Exception")
    })
    public List<Usuario> getUsuarios()
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Usuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUsuario", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdateUsuario")
    @ResponseWrapper(localName = "updateUsuarioResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.UpdateUsuarioResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateUsuarioRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/updateUsuario/Fault/Exception")
    })
    public Usuario updateUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ws.parafarmacia.webservice.Usuario
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newUsuario", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewUsuario")
    @ResponseWrapper(localName = "newUsuarioResponse", targetNamespace = "http://parafarmacia.business.ws.impl/", className = "ws.parafarmacia.webservice.NewUsuarioResponse")
    @Action(input = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newUsuarioRequest", output = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://parafarmacia.business.ws.impl/IParafarmaciaWS/newUsuario/Fault/Exception")
    })
    public Usuario newUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0)
        throws Exception_Exception
    ;

}
