/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo;
import org.xtext.dsl.parafarmacia.parafarmacia.Pagina;
import org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia;
import org.xtext.dsl.parafarmacia.parafarmacia.Producto;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ParafarmaciaLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ParafarmaciaLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Parafarmacia ele) {
    return ele.getTitulo();
  }
  
  public String image(final Parafarmacia ele) {
    return "logo.ico";
  }
  
  public String text(final Producto ele) {
    return ele.getNombre();
  }
  
  public String image(final Producto ele) {
    return "producto.ico";
  }
  
  public String text(final EAttribute ele) {
    String _name = ele.getName();
    String _plus = (_name + ": ");
    Object _defaultValue = ele.getDefaultValue();
    return (_plus + _defaultValue);
  }
  
  public String text(final Cuerpo ele) {
    return "Cuerpo";
  }
  
  public String image(final Pagina ele) {
    return "html.ico";
  }
}
