/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.outline.IOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.xtext.dsl.parafarmacia.ui.AbstractParafarmaciaUiModule;
import org.xtext.dsl.parafarmacia.ui.ParafarmaciaHighlightingCalculator;
import org.xtext.dsl.parafarmacia.ui.ParafarmaciaHighlightingConfiguration;
import org.xtext.dsl.parafarmacia.ui.ParafarmaciaOutlineTransformer;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ParafarmaciaUiModule extends AbstractParafarmaciaUiModule {
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return ParafarmaciaHighlightingConfiguration.class;
  }
  
  public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return ParafarmaciaHighlightingCalculator.class;
  }
  
  @Override
  public Class<? extends IOutlineTreeProvider> bindIOutlineTreeProvider() {
    return ParafarmaciaOutlineTransformer.class;
  }
  
  public ParafarmaciaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
