/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.dsl.parafarmacia.parser.antlr.internal.InternalParafarmaciaParser;
import org.xtext.dsl.parafarmacia.services.ParafarmaciaGrammarAccess;

public class ParafarmaciaParser extends AbstractAntlrParser {

	@Inject
	private ParafarmaciaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalParafarmaciaParser createParser(XtextTokenStream stream) {
		return new InternalParafarmaciaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Parafarmacia";
	}

	public ParafarmaciaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ParafarmaciaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
