/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.dsl.generador.ui.AbstractGeneradorUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GeneradorUiModule extends AbstractGeneradorUiModule {
  public GeneradorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
