/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.generador.generador.Apariencia;
import org.xtext.dsl.generador.generador.GeneradorPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Apariencia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getPrincipal <em>Principal</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getPrincipalClaro <em>Principal Claro</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getSecundario <em>Secundario</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getFondo <em>Fondo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getFondoProductos <em>Fondo Productos</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getPrecios <em>Precios</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getTexto <em>Texto</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getTituloColor <em>Titulo Color</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getNormal <em>Normal</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getGrande <em>Grande</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getMenu <em>Menu</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.AparienciaImpl#getLateral <em>Lateral</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AparienciaImpl extends MinimalEObjectImpl.Container implements Apariencia
{
  /**
   * The default value of the '{@link #getPrincipal() <em>Principal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrincipal()
   * @generated
   * @ordered
   */
  protected static final String PRINCIPAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrincipal() <em>Principal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrincipal()
   * @generated
   * @ordered
   */
  protected String principal = PRINCIPAL_EDEFAULT;

  /**
   * The default value of the '{@link #getPrincipalClaro() <em>Principal Claro</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrincipalClaro()
   * @generated
   * @ordered
   */
  protected static final String PRINCIPAL_CLARO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrincipalClaro() <em>Principal Claro</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrincipalClaro()
   * @generated
   * @ordered
   */
  protected String principalClaro = PRINCIPAL_CLARO_EDEFAULT;

  /**
   * The default value of the '{@link #getSecundario() <em>Secundario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecundario()
   * @generated
   * @ordered
   */
  protected static final String SECUNDARIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecundario() <em>Secundario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecundario()
   * @generated
   * @ordered
   */
  protected String secundario = SECUNDARIO_EDEFAULT;

  /**
   * The default value of the '{@link #getFondo() <em>Fondo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFondo()
   * @generated
   * @ordered
   */
  protected static final String FONDO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFondo() <em>Fondo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFondo()
   * @generated
   * @ordered
   */
  protected String fondo = FONDO_EDEFAULT;

  /**
   * The default value of the '{@link #getFondoProductos() <em>Fondo Productos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFondoProductos()
   * @generated
   * @ordered
   */
  protected static final String FONDO_PRODUCTOS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFondoProductos() <em>Fondo Productos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFondoProductos()
   * @generated
   * @ordered
   */
  protected String fondoProductos = FONDO_PRODUCTOS_EDEFAULT;

  /**
   * The default value of the '{@link #getPrecios() <em>Precios</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecios()
   * @generated
   * @ordered
   */
  protected static final String PRECIOS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrecios() <em>Precios</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecios()
   * @generated
   * @ordered
   */
  protected String precios = PRECIOS_EDEFAULT;

  /**
   * The default value of the '{@link #getTexto() <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexto()
   * @generated
   * @ordered
   */
  protected static final String TEXTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTexto() <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTexto()
   * @generated
   * @ordered
   */
  protected String texto = TEXTO_EDEFAULT;

  /**
   * The default value of the '{@link #getTituloColor() <em>Titulo Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTituloColor()
   * @generated
   * @ordered
   */
  protected static final String TITULO_COLOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTituloColor() <em>Titulo Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTituloColor()
   * @generated
   * @ordered
   */
  protected String tituloColor = TITULO_COLOR_EDEFAULT;

  /**
   * The default value of the '{@link #getNormal() <em>Normal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNormal()
   * @generated
   * @ordered
   */
  protected static final String NORMAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNormal() <em>Normal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNormal()
   * @generated
   * @ordered
   */
  protected String normal = NORMAL_EDEFAULT;

  /**
   * The default value of the '{@link #getGrande() <em>Grande</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrande()
   * @generated
   * @ordered
   */
  protected static final String GRANDE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGrande() <em>Grande</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrande()
   * @generated
   * @ordered
   */
  protected String grande = GRANDE_EDEFAULT;

  /**
   * The default value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected static final String TITULO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected String titulo = TITULO_EDEFAULT;

  /**
   * The default value of the '{@link #getMenu() <em>Menu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMenu()
   * @generated
   * @ordered
   */
  protected static final String MENU_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMenu() <em>Menu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMenu()
   * @generated
   * @ordered
   */
  protected String menu = MENU_EDEFAULT;

  /**
   * The default value of the '{@link #getLateral() <em>Lateral</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLateral()
   * @generated
   * @ordered
   */
  protected static final String LATERAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLateral() <em>Lateral</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLateral()
   * @generated
   * @ordered
   */
  protected String lateral = LATERAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AparienciaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneradorPackage.Literals.APARIENCIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrincipal()
  {
    return principal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrincipal(String newPrincipal)
  {
    String oldPrincipal = principal;
    principal = newPrincipal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__PRINCIPAL, oldPrincipal, principal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrincipalClaro()
  {
    return principalClaro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrincipalClaro(String newPrincipalClaro)
  {
    String oldPrincipalClaro = principalClaro;
    principalClaro = newPrincipalClaro;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__PRINCIPAL_CLARO, oldPrincipalClaro, principalClaro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecundario()
  {
    return secundario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecundario(String newSecundario)
  {
    String oldSecundario = secundario;
    secundario = newSecundario;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__SECUNDARIO, oldSecundario, secundario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFondo()
  {
    return fondo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFondo(String newFondo)
  {
    String oldFondo = fondo;
    fondo = newFondo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__FONDO, oldFondo, fondo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFondoProductos()
  {
    return fondoProductos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFondoProductos(String newFondoProductos)
  {
    String oldFondoProductos = fondoProductos;
    fondoProductos = newFondoProductos;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__FONDO_PRODUCTOS, oldFondoProductos, fondoProductos));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrecios()
  {
    return precios;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrecios(String newPrecios)
  {
    String oldPrecios = precios;
    precios = newPrecios;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__PRECIOS, oldPrecios, precios));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTexto()
  {
    return texto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTexto(String newTexto)
  {
    String oldTexto = texto;
    texto = newTexto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__TEXTO, oldTexto, texto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTituloColor()
  {
    return tituloColor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTituloColor(String newTituloColor)
  {
    String oldTituloColor = tituloColor;
    tituloColor = newTituloColor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__TITULO_COLOR, oldTituloColor, tituloColor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNormal()
  {
    return normal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNormal(String newNormal)
  {
    String oldNormal = normal;
    normal = newNormal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__NORMAL, oldNormal, normal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getGrande()
  {
    return grande;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGrande(String newGrande)
  {
    String oldGrande = grande;
    grande = newGrande;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__GRANDE, oldGrande, grande));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitulo()
  {
    return titulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitulo(String newTitulo)
  {
    String oldTitulo = titulo;
    titulo = newTitulo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__TITULO, oldTitulo, titulo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMenu()
  {
    return menu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMenu(String newMenu)
  {
    String oldMenu = menu;
    menu = newMenu;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__MENU, oldMenu, menu));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLateral()
  {
    return lateral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLateral(String newLateral)
  {
    String oldLateral = lateral;
    lateral = newLateral;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.APARIENCIA__LATERAL, oldLateral, lateral));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneradorPackage.APARIENCIA__PRINCIPAL:
        return getPrincipal();
      case GeneradorPackage.APARIENCIA__PRINCIPAL_CLARO:
        return getPrincipalClaro();
      case GeneradorPackage.APARIENCIA__SECUNDARIO:
        return getSecundario();
      case GeneradorPackage.APARIENCIA__FONDO:
        return getFondo();
      case GeneradorPackage.APARIENCIA__FONDO_PRODUCTOS:
        return getFondoProductos();
      case GeneradorPackage.APARIENCIA__PRECIOS:
        return getPrecios();
      case GeneradorPackage.APARIENCIA__TEXTO:
        return getTexto();
      case GeneradorPackage.APARIENCIA__TITULO_COLOR:
        return getTituloColor();
      case GeneradorPackage.APARIENCIA__NORMAL:
        return getNormal();
      case GeneradorPackage.APARIENCIA__GRANDE:
        return getGrande();
      case GeneradorPackage.APARIENCIA__TITULO:
        return getTitulo();
      case GeneradorPackage.APARIENCIA__MENU:
        return getMenu();
      case GeneradorPackage.APARIENCIA__LATERAL:
        return getLateral();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneradorPackage.APARIENCIA__PRINCIPAL:
        setPrincipal((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__PRINCIPAL_CLARO:
        setPrincipalClaro((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__SECUNDARIO:
        setSecundario((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__FONDO:
        setFondo((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__FONDO_PRODUCTOS:
        setFondoProductos((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__PRECIOS:
        setPrecios((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__TEXTO:
        setTexto((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__TITULO_COLOR:
        setTituloColor((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__NORMAL:
        setNormal((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__GRANDE:
        setGrande((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__TITULO:
        setTitulo((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__MENU:
        setMenu((String)newValue);
        return;
      case GeneradorPackage.APARIENCIA__LATERAL:
        setLateral((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.APARIENCIA__PRINCIPAL:
        setPrincipal(PRINCIPAL_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__PRINCIPAL_CLARO:
        setPrincipalClaro(PRINCIPAL_CLARO_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__SECUNDARIO:
        setSecundario(SECUNDARIO_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__FONDO:
        setFondo(FONDO_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__FONDO_PRODUCTOS:
        setFondoProductos(FONDO_PRODUCTOS_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__PRECIOS:
        setPrecios(PRECIOS_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__TEXTO:
        setTexto(TEXTO_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__TITULO_COLOR:
        setTituloColor(TITULO_COLOR_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__NORMAL:
        setNormal(NORMAL_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__GRANDE:
        setGrande(GRANDE_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__TITULO:
        setTitulo(TITULO_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__MENU:
        setMenu(MENU_EDEFAULT);
        return;
      case GeneradorPackage.APARIENCIA__LATERAL:
        setLateral(LATERAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.APARIENCIA__PRINCIPAL:
        return PRINCIPAL_EDEFAULT == null ? principal != null : !PRINCIPAL_EDEFAULT.equals(principal);
      case GeneradorPackage.APARIENCIA__PRINCIPAL_CLARO:
        return PRINCIPAL_CLARO_EDEFAULT == null ? principalClaro != null : !PRINCIPAL_CLARO_EDEFAULT.equals(principalClaro);
      case GeneradorPackage.APARIENCIA__SECUNDARIO:
        return SECUNDARIO_EDEFAULT == null ? secundario != null : !SECUNDARIO_EDEFAULT.equals(secundario);
      case GeneradorPackage.APARIENCIA__FONDO:
        return FONDO_EDEFAULT == null ? fondo != null : !FONDO_EDEFAULT.equals(fondo);
      case GeneradorPackage.APARIENCIA__FONDO_PRODUCTOS:
        return FONDO_PRODUCTOS_EDEFAULT == null ? fondoProductos != null : !FONDO_PRODUCTOS_EDEFAULT.equals(fondoProductos);
      case GeneradorPackage.APARIENCIA__PRECIOS:
        return PRECIOS_EDEFAULT == null ? precios != null : !PRECIOS_EDEFAULT.equals(precios);
      case GeneradorPackage.APARIENCIA__TEXTO:
        return TEXTO_EDEFAULT == null ? texto != null : !TEXTO_EDEFAULT.equals(texto);
      case GeneradorPackage.APARIENCIA__TITULO_COLOR:
        return TITULO_COLOR_EDEFAULT == null ? tituloColor != null : !TITULO_COLOR_EDEFAULT.equals(tituloColor);
      case GeneradorPackage.APARIENCIA__NORMAL:
        return NORMAL_EDEFAULT == null ? normal != null : !NORMAL_EDEFAULT.equals(normal);
      case GeneradorPackage.APARIENCIA__GRANDE:
        return GRANDE_EDEFAULT == null ? grande != null : !GRANDE_EDEFAULT.equals(grande);
      case GeneradorPackage.APARIENCIA__TITULO:
        return TITULO_EDEFAULT == null ? titulo != null : !TITULO_EDEFAULT.equals(titulo);
      case GeneradorPackage.APARIENCIA__MENU:
        return MENU_EDEFAULT == null ? menu != null : !MENU_EDEFAULT.equals(menu);
      case GeneradorPackage.APARIENCIA__LATERAL:
        return LATERAL_EDEFAULT == null ? lateral != null : !LATERAL_EDEFAULT.equals(lateral);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (principal: ");
    result.append(principal);
    result.append(", principalClaro: ");
    result.append(principalClaro);
    result.append(", secundario: ");
    result.append(secundario);
    result.append(", fondo: ");
    result.append(fondo);
    result.append(", fondoProductos: ");
    result.append(fondoProductos);
    result.append(", precios: ");
    result.append(precios);
    result.append(", texto: ");
    result.append(texto);
    result.append(", tituloColor: ");
    result.append(tituloColor);
    result.append(", normal: ");
    result.append(normal);
    result.append(", grande: ");
    result.append(grande);
    result.append(", titulo: ");
    result.append(titulo);
    result.append(", menu: ");
    result.append(menu);
    result.append(", lateral: ");
    result.append(lateral);
    result.append(')');
    return result.toString();
  }

} //AparienciaImpl
