/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.dsl.generador.generador.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GeneradorFactoryImpl extends EFactoryImpl implements GeneradorFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GeneradorFactory init()
  {
    try
    {
      GeneradorFactory theGeneradorFactory = (GeneradorFactory)EPackage.Registry.INSTANCE.getEFactory(GeneradorPackage.eNS_URI);
      if (theGeneradorFactory != null)
      {
        return theGeneradorFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GeneradorFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GeneradorFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GeneradorPackage.PARAFARMACIA: return createParafarmacia();
      case GeneradorPackage.APARIENCIA: return createApariencia();
      case GeneradorPackage.PRODUCTO: return createProducto();
      case GeneradorPackage.TIPO: return createTipo();
      case GeneradorPackage.DESPLEGABLE: return createDesplegable();
      case GeneradorPackage.PERMANENTE: return createPermanente();
      case GeneradorPackage.REGISTRO: return createRegistro();
      case GeneradorPackage.DIRECCION: return createDireccion();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parafarmacia createParafarmacia()
  {
    ParafarmaciaImpl parafarmacia = new ParafarmaciaImpl();
    return parafarmacia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Apariencia createApariencia()
  {
    AparienciaImpl apariencia = new AparienciaImpl();
    return apariencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Producto createProducto()
  {
    ProductoImpl producto = new ProductoImpl();
    return producto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tipo createTipo()
  {
    TipoImpl tipo = new TipoImpl();
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Desplegable createDesplegable()
  {
    DesplegableImpl desplegable = new DesplegableImpl();
    return desplegable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Permanente createPermanente()
  {
    PermanenteImpl permanente = new PermanenteImpl();
    return permanente;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Registro createRegistro()
  {
    RegistroImpl registro = new RegistroImpl();
    return registro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Direccion createDireccion()
  {
    DireccionImpl direccion = new DireccionImpl();
    return direccion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GeneradorPackage getGeneradorPackage()
  {
    return (GeneradorPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GeneradorPackage getPackage()
  {
    return GeneradorPackage.eINSTANCE;
  }

} //GeneradorFactoryImpl
