/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.dsl.generador.generador.Apariencia;
import org.xtext.dsl.generador.generador.Direccion;
import org.xtext.dsl.generador.generador.GeneradorPackage;
import org.xtext.dsl.generador.generador.Parafarmacia;
import org.xtext.dsl.generador.generador.Producto;
import org.xtext.dsl.generador.generador.Registro;
import org.xtext.dsl.generador.generador.Tipo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parafarmacia</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getFuente <em>Fuente</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getDireccion <em>Direccion</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getCif <em>Cif</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getRegistro <em>Registro</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getCorreo <em>Correo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getTelefono <em>Telefono</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getApariencia <em>Apariencia</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getCategorias <em>Categorias</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getNumProductosPorFila <em>Num Productos Por Fila</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getProductos <em>Productos</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getNombreUsuario <em>Nombre Usuario</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ParafarmaciaImpl#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParafarmaciaImpl extends MinimalEObjectImpl.Container implements Parafarmacia
{
  /**
   * The default value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected static final String TITULO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitulo() <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitulo()
   * @generated
   * @ordered
   */
  protected String titulo = TITULO_EDEFAULT;

  /**
   * The default value of the '{@link #getFuente() <em>Fuente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuente()
   * @generated
   * @ordered
   */
  protected static final String FUENTE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFuente() <em>Fuente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuente()
   * @generated
   * @ordered
   */
  protected String fuente = FUENTE_EDEFAULT;

  /**
   * The default value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected String nombre = NOMBRE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDireccion() <em>Direccion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDireccion()
   * @generated
   * @ordered
   */
  protected Direccion direccion;

  /**
   * The default value of the '{@link #getCif() <em>Cif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCif()
   * @generated
   * @ordered
   */
  protected static final String CIF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCif() <em>Cif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCif()
   * @generated
   * @ordered
   */
  protected String cif = CIF_EDEFAULT;

  /**
   * The cached value of the '{@link #getRegistro() <em>Registro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegistro()
   * @generated
   * @ordered
   */
  protected Registro registro;

  /**
   * The default value of the '{@link #getCorreo() <em>Correo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorreo()
   * @generated
   * @ordered
   */
  protected static final String CORREO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCorreo() <em>Correo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCorreo()
   * @generated
   * @ordered
   */
  protected String correo = CORREO_EDEFAULT;

  /**
   * The default value of the '{@link #getTelefono() <em>Telefono</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTelefono()
   * @generated
   * @ordered
   */
  protected static final int TELEFONO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTelefono() <em>Telefono</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTelefono()
   * @generated
   * @ordered
   */
  protected int telefono = TELEFONO_EDEFAULT;

  /**
   * The cached value of the '{@link #getTipo() <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTipo()
   * @generated
   * @ordered
   */
  protected Tipo tipo;

  /**
   * The cached value of the '{@link #getApariencia() <em>Apariencia</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApariencia()
   * @generated
   * @ordered
   */
  protected Apariencia apariencia;

  /**
   * The cached value of the '{@link #getCategorias() <em>Categorias</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategorias()
   * @generated
   * @ordered
   */
  protected EList<String> categorias;

  /**
   * The default value of the '{@link #getNumProductosPorFila() <em>Num Productos Por Fila</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumProductosPorFila()
   * @generated
   * @ordered
   */
  protected static final int NUM_PRODUCTOS_POR_FILA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumProductosPorFila() <em>Num Productos Por Fila</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumProductosPorFila()
   * @generated
   * @ordered
   */
  protected int numProductosPorFila = NUM_PRODUCTOS_POR_FILA_EDEFAULT;

  /**
   * The cached value of the '{@link #getProductos() <em>Productos</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProductos()
   * @generated
   * @ordered
   */
  protected EList<Producto> productos;

  /**
   * The default value of the '{@link #getNombreUsuario() <em>Nombre Usuario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreUsuario()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_USUARIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombreUsuario() <em>Nombre Usuario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreUsuario()
   * @generated
   * @ordered
   */
  protected String nombreUsuario = NOMBRE_USUARIO_EDEFAULT;

  /**
   * The default value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected static final String EMAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEmail() <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEmail()
   * @generated
   * @ordered
   */
  protected String email = EMAIL_EDEFAULT;

  /**
   * The default value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected static final String PASSWORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected String password = PASSWORD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParafarmaciaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneradorPackage.Literals.PARAFARMACIA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitulo()
  {
    return titulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitulo(String newTitulo)
  {
    String oldTitulo = titulo;
    titulo = newTitulo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__TITULO, oldTitulo, titulo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFuente()
  {
    return fuente;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFuente(String newFuente)
  {
    String oldFuente = fuente;
    fuente = newFuente;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__FUENTE, oldFuente, fuente));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombre(String newNombre)
  {
    String oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__NOMBRE, oldNombre, nombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Direccion getDireccion()
  {
    return direccion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDireccion(Direccion newDireccion, NotificationChain msgs)
  {
    Direccion oldDireccion = direccion;
    direccion = newDireccion;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__DIRECCION, oldDireccion, newDireccion);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDireccion(Direccion newDireccion)
  {
    if (newDireccion != direccion)
    {
      NotificationChain msgs = null;
      if (direccion != null)
        msgs = ((InternalEObject)direccion).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__DIRECCION, null, msgs);
      if (newDireccion != null)
        msgs = ((InternalEObject)newDireccion).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__DIRECCION, null, msgs);
      msgs = basicSetDireccion(newDireccion, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__DIRECCION, newDireccion, newDireccion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCif()
  {
    return cif;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCif(String newCif)
  {
    String oldCif = cif;
    cif = newCif;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__CIF, oldCif, cif));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Registro getRegistro()
  {
    return registro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRegistro(Registro newRegistro, NotificationChain msgs)
  {
    Registro oldRegistro = registro;
    registro = newRegistro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__REGISTRO, oldRegistro, newRegistro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRegistro(Registro newRegistro)
  {
    if (newRegistro != registro)
    {
      NotificationChain msgs = null;
      if (registro != null)
        msgs = ((InternalEObject)registro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__REGISTRO, null, msgs);
      if (newRegistro != null)
        msgs = ((InternalEObject)newRegistro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__REGISTRO, null, msgs);
      msgs = basicSetRegistro(newRegistro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__REGISTRO, newRegistro, newRegistro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCorreo()
  {
    return correo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCorreo(String newCorreo)
  {
    String oldCorreo = correo;
    correo = newCorreo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__CORREO, oldCorreo, correo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTelefono()
  {
    return telefono;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTelefono(int newTelefono)
  {
    int oldTelefono = telefono;
    telefono = newTelefono;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__TELEFONO, oldTelefono, telefono));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tipo getTipo()
  {
    return tipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTipo(Tipo newTipo, NotificationChain msgs)
  {
    Tipo oldTipo = tipo;
    tipo = newTipo;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__TIPO, oldTipo, newTipo);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTipo(Tipo newTipo)
  {
    if (newTipo != tipo)
    {
      NotificationChain msgs = null;
      if (tipo != null)
        msgs = ((InternalEObject)tipo).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__TIPO, null, msgs);
      if (newTipo != null)
        msgs = ((InternalEObject)newTipo).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__TIPO, null, msgs);
      msgs = basicSetTipo(newTipo, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__TIPO, newTipo, newTipo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Apariencia getApariencia()
  {
    return apariencia;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetApariencia(Apariencia newApariencia, NotificationChain msgs)
  {
    Apariencia oldApariencia = apariencia;
    apariencia = newApariencia;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__APARIENCIA, oldApariencia, newApariencia);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setApariencia(Apariencia newApariencia)
  {
    if (newApariencia != apariencia)
    {
      NotificationChain msgs = null;
      if (apariencia != null)
        msgs = ((InternalEObject)apariencia).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__APARIENCIA, null, msgs);
      if (newApariencia != null)
        msgs = ((InternalEObject)newApariencia).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GeneradorPackage.PARAFARMACIA__APARIENCIA, null, msgs);
      msgs = basicSetApariencia(newApariencia, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__APARIENCIA, newApariencia, newApariencia));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getCategorias()
  {
    if (categorias == null)
    {
      categorias = new EDataTypeEList<String>(String.class, this, GeneradorPackage.PARAFARMACIA__CATEGORIAS);
    }
    return categorias;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getNumProductosPorFila()
  {
    return numProductosPorFila;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNumProductosPorFila(int newNumProductosPorFila)
  {
    int oldNumProductosPorFila = numProductosPorFila;
    numProductosPorFila = newNumProductosPorFila;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__NUM_PRODUCTOS_POR_FILA, oldNumProductosPorFila, numProductosPorFila));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Producto> getProductos()
  {
    if (productos == null)
    {
      productos = new EObjectContainmentEList<Producto>(Producto.class, this, GeneradorPackage.PARAFARMACIA__PRODUCTOS);
    }
    return productos;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombreUsuario()
  {
    return nombreUsuario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombreUsuario(String newNombreUsuario)
  {
    String oldNombreUsuario = nombreUsuario;
    nombreUsuario = newNombreUsuario;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__NOMBRE_USUARIO, oldNombreUsuario, nombreUsuario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEmail()
  {
    return email;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEmail(String newEmail)
  {
    String oldEmail = email;
    email = newEmail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__EMAIL, oldEmail, email));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPassword()
  {
    return password;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPassword(String newPassword)
  {
    String oldPassword = password;
    password = newPassword;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PARAFARMACIA__PASSWORD, oldPassword, password));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GeneradorPackage.PARAFARMACIA__DIRECCION:
        return basicSetDireccion(null, msgs);
      case GeneradorPackage.PARAFARMACIA__REGISTRO:
        return basicSetRegistro(null, msgs);
      case GeneradorPackage.PARAFARMACIA__TIPO:
        return basicSetTipo(null, msgs);
      case GeneradorPackage.PARAFARMACIA__APARIENCIA:
        return basicSetApariencia(null, msgs);
      case GeneradorPackage.PARAFARMACIA__PRODUCTOS:
        return ((InternalEList<?>)getProductos()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneradorPackage.PARAFARMACIA__TITULO:
        return getTitulo();
      case GeneradorPackage.PARAFARMACIA__FUENTE:
        return getFuente();
      case GeneradorPackage.PARAFARMACIA__NOMBRE:
        return getNombre();
      case GeneradorPackage.PARAFARMACIA__DIRECCION:
        return getDireccion();
      case GeneradorPackage.PARAFARMACIA__CIF:
        return getCif();
      case GeneradorPackage.PARAFARMACIA__REGISTRO:
        return getRegistro();
      case GeneradorPackage.PARAFARMACIA__CORREO:
        return getCorreo();
      case GeneradorPackage.PARAFARMACIA__TELEFONO:
        return getTelefono();
      case GeneradorPackage.PARAFARMACIA__TIPO:
        return getTipo();
      case GeneradorPackage.PARAFARMACIA__APARIENCIA:
        return getApariencia();
      case GeneradorPackage.PARAFARMACIA__CATEGORIAS:
        return getCategorias();
      case GeneradorPackage.PARAFARMACIA__NUM_PRODUCTOS_POR_FILA:
        return getNumProductosPorFila();
      case GeneradorPackage.PARAFARMACIA__PRODUCTOS:
        return getProductos();
      case GeneradorPackage.PARAFARMACIA__NOMBRE_USUARIO:
        return getNombreUsuario();
      case GeneradorPackage.PARAFARMACIA__EMAIL:
        return getEmail();
      case GeneradorPackage.PARAFARMACIA__PASSWORD:
        return getPassword();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneradorPackage.PARAFARMACIA__TITULO:
        setTitulo((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__FUENTE:
        setFuente((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__NOMBRE:
        setNombre((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__DIRECCION:
        setDireccion((Direccion)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__CIF:
        setCif((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__REGISTRO:
        setRegistro((Registro)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__CORREO:
        setCorreo((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__TELEFONO:
        setTelefono((Integer)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__TIPO:
        setTipo((Tipo)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__APARIENCIA:
        setApariencia((Apariencia)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__CATEGORIAS:
        getCategorias().clear();
        getCategorias().addAll((Collection<? extends String>)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__NUM_PRODUCTOS_POR_FILA:
        setNumProductosPorFila((Integer)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__PRODUCTOS:
        getProductos().clear();
        getProductos().addAll((Collection<? extends Producto>)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__NOMBRE_USUARIO:
        setNombreUsuario((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__EMAIL:
        setEmail((String)newValue);
        return;
      case GeneradorPackage.PARAFARMACIA__PASSWORD:
        setPassword((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.PARAFARMACIA__TITULO:
        setTitulo(TITULO_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__FUENTE:
        setFuente(FUENTE_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__NOMBRE:
        setNombre(NOMBRE_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__DIRECCION:
        setDireccion((Direccion)null);
        return;
      case GeneradorPackage.PARAFARMACIA__CIF:
        setCif(CIF_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__REGISTRO:
        setRegistro((Registro)null);
        return;
      case GeneradorPackage.PARAFARMACIA__CORREO:
        setCorreo(CORREO_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__TELEFONO:
        setTelefono(TELEFONO_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__TIPO:
        setTipo((Tipo)null);
        return;
      case GeneradorPackage.PARAFARMACIA__APARIENCIA:
        setApariencia((Apariencia)null);
        return;
      case GeneradorPackage.PARAFARMACIA__CATEGORIAS:
        getCategorias().clear();
        return;
      case GeneradorPackage.PARAFARMACIA__NUM_PRODUCTOS_POR_FILA:
        setNumProductosPorFila(NUM_PRODUCTOS_POR_FILA_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__PRODUCTOS:
        getProductos().clear();
        return;
      case GeneradorPackage.PARAFARMACIA__NOMBRE_USUARIO:
        setNombreUsuario(NOMBRE_USUARIO_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__EMAIL:
        setEmail(EMAIL_EDEFAULT);
        return;
      case GeneradorPackage.PARAFARMACIA__PASSWORD:
        setPassword(PASSWORD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.PARAFARMACIA__TITULO:
        return TITULO_EDEFAULT == null ? titulo != null : !TITULO_EDEFAULT.equals(titulo);
      case GeneradorPackage.PARAFARMACIA__FUENTE:
        return FUENTE_EDEFAULT == null ? fuente != null : !FUENTE_EDEFAULT.equals(fuente);
      case GeneradorPackage.PARAFARMACIA__NOMBRE:
        return NOMBRE_EDEFAULT == null ? nombre != null : !NOMBRE_EDEFAULT.equals(nombre);
      case GeneradorPackage.PARAFARMACIA__DIRECCION:
        return direccion != null;
      case GeneradorPackage.PARAFARMACIA__CIF:
        return CIF_EDEFAULT == null ? cif != null : !CIF_EDEFAULT.equals(cif);
      case GeneradorPackage.PARAFARMACIA__REGISTRO:
        return registro != null;
      case GeneradorPackage.PARAFARMACIA__CORREO:
        return CORREO_EDEFAULT == null ? correo != null : !CORREO_EDEFAULT.equals(correo);
      case GeneradorPackage.PARAFARMACIA__TELEFONO:
        return telefono != TELEFONO_EDEFAULT;
      case GeneradorPackage.PARAFARMACIA__TIPO:
        return tipo != null;
      case GeneradorPackage.PARAFARMACIA__APARIENCIA:
        return apariencia != null;
      case GeneradorPackage.PARAFARMACIA__CATEGORIAS:
        return categorias != null && !categorias.isEmpty();
      case GeneradorPackage.PARAFARMACIA__NUM_PRODUCTOS_POR_FILA:
        return numProductosPorFila != NUM_PRODUCTOS_POR_FILA_EDEFAULT;
      case GeneradorPackage.PARAFARMACIA__PRODUCTOS:
        return productos != null && !productos.isEmpty();
      case GeneradorPackage.PARAFARMACIA__NOMBRE_USUARIO:
        return NOMBRE_USUARIO_EDEFAULT == null ? nombreUsuario != null : !NOMBRE_USUARIO_EDEFAULT.equals(nombreUsuario);
      case GeneradorPackage.PARAFARMACIA__EMAIL:
        return EMAIL_EDEFAULT == null ? email != null : !EMAIL_EDEFAULT.equals(email);
      case GeneradorPackage.PARAFARMACIA__PASSWORD:
        return PASSWORD_EDEFAULT == null ? password != null : !PASSWORD_EDEFAULT.equals(password);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (titulo: ");
    result.append(titulo);
    result.append(", fuente: ");
    result.append(fuente);
    result.append(", nombre: ");
    result.append(nombre);
    result.append(", cif: ");
    result.append(cif);
    result.append(", correo: ");
    result.append(correo);
    result.append(", telefono: ");
    result.append(telefono);
    result.append(", categorias: ");
    result.append(categorias);
    result.append(", numProductosPorFila: ");
    result.append(numProductosPorFila);
    result.append(", nombreUsuario: ");
    result.append(nombreUsuario);
    result.append(", email: ");
    result.append(email);
    result.append(", password: ");
    result.append(password);
    result.append(')');
    return result.toString();
  }

} //ParafarmaciaImpl
