/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.generador.generador.GeneradorPackage;
import org.xtext.dsl.generador.generador.Producto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Producto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ProductoImpl#getNombreProducto <em>Nombre Producto</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ProductoImpl#getDescripcion <em>Descripcion</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ProductoImpl#getPrecio <em>Precio</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ProductoImpl#getCantidad <em>Cantidad</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.ProductoImpl#getCategoria <em>Categoria</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProductoImpl extends MinimalEObjectImpl.Container implements Producto
{
  /**
   * The default value of the '{@link #getNombreProducto() <em>Nombre Producto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreProducto()
   * @generated
   * @ordered
   */
  protected static final String NOMBRE_PRODUCTO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNombreProducto() <em>Nombre Producto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombreProducto()
   * @generated
   * @ordered
   */
  protected String nombreProducto = NOMBRE_PRODUCTO_EDEFAULT;

  /**
   * The default value of the '{@link #getDescripcion() <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescripcion()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPCION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescripcion() <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescripcion()
   * @generated
   * @ordered
   */
  protected String descripcion = DESCRIPCION_EDEFAULT;

  /**
   * The default value of the '{@link #getPrecio() <em>Precio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecio()
   * @generated
   * @ordered
   */
  protected static final String PRECIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPrecio() <em>Precio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrecio()
   * @generated
   * @ordered
   */
  protected String precio = PRECIO_EDEFAULT;

  /**
   * The default value of the '{@link #getCantidad() <em>Cantidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCantidad()
   * @generated
   * @ordered
   */
  protected static final int CANTIDAD_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCantidad() <em>Cantidad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCantidad()
   * @generated
   * @ordered
   */
  protected int cantidad = CANTIDAD_EDEFAULT;

  /**
   * The default value of the '{@link #getCategoria() <em>Categoria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategoria()
   * @generated
   * @ordered
   */
  protected static final String CATEGORIA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCategoria() <em>Categoria</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCategoria()
   * @generated
   * @ordered
   */
  protected String categoria = CATEGORIA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProductoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneradorPackage.Literals.PRODUCTO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getNombreProducto()
  {
    return nombreProducto;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNombreProducto(String newNombreProducto)
  {
    String oldNombreProducto = nombreProducto;
    nombreProducto = newNombreProducto;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PRODUCTO__NOMBRE_PRODUCTO, oldNombreProducto, nombreProducto));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDescripcion()
  {
    return descripcion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescripcion(String newDescripcion)
  {
    String oldDescripcion = descripcion;
    descripcion = newDescripcion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PRODUCTO__DESCRIPCION, oldDescripcion, descripcion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPrecio()
  {
    return precio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrecio(String newPrecio)
  {
    String oldPrecio = precio;
    precio = newPrecio;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PRODUCTO__PRECIO, oldPrecio, precio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getCantidad()
  {
    return cantidad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCantidad(int newCantidad)
  {
    int oldCantidad = cantidad;
    cantidad = newCantidad;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PRODUCTO__CANTIDAD, oldCantidad, cantidad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCategoria()
  {
    return categoria;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCategoria(String newCategoria)
  {
    String oldCategoria = categoria;
    categoria = newCategoria;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.PRODUCTO__CATEGORIA, oldCategoria, categoria));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneradorPackage.PRODUCTO__NOMBRE_PRODUCTO:
        return getNombreProducto();
      case GeneradorPackage.PRODUCTO__DESCRIPCION:
        return getDescripcion();
      case GeneradorPackage.PRODUCTO__PRECIO:
        return getPrecio();
      case GeneradorPackage.PRODUCTO__CANTIDAD:
        return getCantidad();
      case GeneradorPackage.PRODUCTO__CATEGORIA:
        return getCategoria();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneradorPackage.PRODUCTO__NOMBRE_PRODUCTO:
        setNombreProducto((String)newValue);
        return;
      case GeneradorPackage.PRODUCTO__DESCRIPCION:
        setDescripcion((String)newValue);
        return;
      case GeneradorPackage.PRODUCTO__PRECIO:
        setPrecio((String)newValue);
        return;
      case GeneradorPackage.PRODUCTO__CANTIDAD:
        setCantidad((Integer)newValue);
        return;
      case GeneradorPackage.PRODUCTO__CATEGORIA:
        setCategoria((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.PRODUCTO__NOMBRE_PRODUCTO:
        setNombreProducto(NOMBRE_PRODUCTO_EDEFAULT);
        return;
      case GeneradorPackage.PRODUCTO__DESCRIPCION:
        setDescripcion(DESCRIPCION_EDEFAULT);
        return;
      case GeneradorPackage.PRODUCTO__PRECIO:
        setPrecio(PRECIO_EDEFAULT);
        return;
      case GeneradorPackage.PRODUCTO__CANTIDAD:
        setCantidad(CANTIDAD_EDEFAULT);
        return;
      case GeneradorPackage.PRODUCTO__CATEGORIA:
        setCategoria(CATEGORIA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.PRODUCTO__NOMBRE_PRODUCTO:
        return NOMBRE_PRODUCTO_EDEFAULT == null ? nombreProducto != null : !NOMBRE_PRODUCTO_EDEFAULT.equals(nombreProducto);
      case GeneradorPackage.PRODUCTO__DESCRIPCION:
        return DESCRIPCION_EDEFAULT == null ? descripcion != null : !DESCRIPCION_EDEFAULT.equals(descripcion);
      case GeneradorPackage.PRODUCTO__PRECIO:
        return PRECIO_EDEFAULT == null ? precio != null : !PRECIO_EDEFAULT.equals(precio);
      case GeneradorPackage.PRODUCTO__CANTIDAD:
        return cantidad != CANTIDAD_EDEFAULT;
      case GeneradorPackage.PRODUCTO__CATEGORIA:
        return CATEGORIA_EDEFAULT == null ? categoria != null : !CATEGORIA_EDEFAULT.equals(categoria);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (nombreProducto: ");
    result.append(nombreProducto);
    result.append(", descripcion: ");
    result.append(descripcion);
    result.append(", precio: ");
    result.append(precio);
    result.append(", cantidad: ");
    result.append(cantidad);
    result.append(", categoria: ");
    result.append(categoria);
    result.append(')');
    return result.toString();
  }

} //ProductoImpl
