/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dsl.generador.generador.GeneradorPackage;
import org.xtext.dsl.generador.generador.Registro;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Registro</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.RegistroImpl#getTomo <em>Tomo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.RegistroImpl#getFolio <em>Folio</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.RegistroImpl#getSeccion <em>Seccion</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.impl.RegistroImpl#getHoja <em>Hoja</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RegistroImpl extends MinimalEObjectImpl.Container implements Registro
{
  /**
   * The default value of the '{@link #getTomo() <em>Tomo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTomo()
   * @generated
   * @ordered
   */
  protected static final int TOMO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTomo() <em>Tomo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTomo()
   * @generated
   * @ordered
   */
  protected int tomo = TOMO_EDEFAULT;

  /**
   * The default value of the '{@link #getFolio() <em>Folio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFolio()
   * @generated
   * @ordered
   */
  protected static final int FOLIO_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFolio() <em>Folio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFolio()
   * @generated
   * @ordered
   */
  protected int folio = FOLIO_EDEFAULT;

  /**
   * The default value of the '{@link #getSeccion() <em>Seccion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeccion()
   * @generated
   * @ordered
   */
  protected static final int SECCION_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSeccion() <em>Seccion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeccion()
   * @generated
   * @ordered
   */
  protected int seccion = SECCION_EDEFAULT;

  /**
   * The default value of the '{@link #getHoja() <em>Hoja</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHoja()
   * @generated
   * @ordered
   */
  protected static final int HOJA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHoja() <em>Hoja</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHoja()
   * @generated
   * @ordered
   */
  protected int hoja = HOJA_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegistroImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneradorPackage.Literals.REGISTRO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTomo()
  {
    return tomo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTomo(int newTomo)
  {
    int oldTomo = tomo;
    tomo = newTomo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.REGISTRO__TOMO, oldTomo, tomo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getFolio()
  {
    return folio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFolio(int newFolio)
  {
    int oldFolio = folio;
    folio = newFolio;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.REGISTRO__FOLIO, oldFolio, folio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSeccion()
  {
    return seccion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSeccion(int newSeccion)
  {
    int oldSeccion = seccion;
    seccion = newSeccion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.REGISTRO__SECCION, oldSeccion, seccion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getHoja()
  {
    return hoja;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHoja(int newHoja)
  {
    int oldHoja = hoja;
    hoja = newHoja;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GeneradorPackage.REGISTRO__HOJA, oldHoja, hoja));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneradorPackage.REGISTRO__TOMO:
        return getTomo();
      case GeneradorPackage.REGISTRO__FOLIO:
        return getFolio();
      case GeneradorPackage.REGISTRO__SECCION:
        return getSeccion();
      case GeneradorPackage.REGISTRO__HOJA:
        return getHoja();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneradorPackage.REGISTRO__TOMO:
        setTomo((Integer)newValue);
        return;
      case GeneradorPackage.REGISTRO__FOLIO:
        setFolio((Integer)newValue);
        return;
      case GeneradorPackage.REGISTRO__SECCION:
        setSeccion((Integer)newValue);
        return;
      case GeneradorPackage.REGISTRO__HOJA:
        setHoja((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.REGISTRO__TOMO:
        setTomo(TOMO_EDEFAULT);
        return;
      case GeneradorPackage.REGISTRO__FOLIO:
        setFolio(FOLIO_EDEFAULT);
        return;
      case GeneradorPackage.REGISTRO__SECCION:
        setSeccion(SECCION_EDEFAULT);
        return;
      case GeneradorPackage.REGISTRO__HOJA:
        setHoja(HOJA_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneradorPackage.REGISTRO__TOMO:
        return tomo != TOMO_EDEFAULT;
      case GeneradorPackage.REGISTRO__FOLIO:
        return folio != FOLIO_EDEFAULT;
      case GeneradorPackage.REGISTRO__SECCION:
        return seccion != SECCION_EDEFAULT;
      case GeneradorPackage.REGISTRO__HOJA:
        return hoja != HOJA_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (tomo: ");
    result.append(tomo);
    result.append(", folio: ");
    result.append(folio);
    result.append(", seccion: ");
    result.append(seccion);
    result.append(", hoja: ");
    result.append(hoja);
    result.append(')');
    return result.toString();
  }

} //RegistroImpl
