/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class ParafarmaciaWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public ParafarmaciaWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
