/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pagina</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getCuerpo <em>Cuerpo</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getPagina()
 * @model
 * @generated
 */
public interface Pagina extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getPagina_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titulo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titulo</em>' attribute.
   * @see #setTitulo(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getPagina_Titulo()
   * @model
   * @generated
   */
  String getTitulo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getTitulo <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titulo</em>' attribute.
   * @see #getTitulo()
   * @generated
   */
  void setTitulo(String value);

  /**
   * Returns the value of the '<em><b>Cuerpo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cuerpo</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cuerpo</em>' containment reference.
   * @see #setCuerpo(Cuerpo)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getPagina_Cuerpo()
   * @model containment="true"
   * @generated
   */
  Cuerpo getCuerpo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getCuerpo <em>Cuerpo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cuerpo</em>' containment reference.
   * @see #getCuerpo()
   * @generated
   */
  void setCuerpo(Cuerpo value);

} // Pagina
