/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaFactory
 * @model kind="package"
 * @generated
 */
public interface ParafarmaciaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "parafarmacia";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/dsl/parafarmacia/Parafarmacia";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "parafarmacia";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ParafarmaciaPackage eINSTANCE = org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaImpl <em>Parafarmacia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaImpl
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getParafarmacia()
   * @generated
   */
  int PARAFARMACIA = 0;

  /**
   * The feature id for the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAFARMACIA__TITULO = 0;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAFARMACIA__DESCRIPCION = 1;

  /**
   * The feature id for the '<em><b>Apariencia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAFARMACIA__APARIENCIA = 2;

  /**
   * The feature id for the '<em><b>Paginas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAFARMACIA__PAGINAS = 3;

  /**
   * The number of structural features of the '<em>Parafarmacia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAFARMACIA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl <em>Apariencia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getApariencia()
   * @generated
   */
  int APARIENCIA = 1;

  /**
   * The feature id for the '<em><b>Color Fondo1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__COLOR_FONDO1 = 0;

  /**
   * The feature id for the '<em><b>Color Fondo2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__COLOR_FONDO2 = 1;

  /**
   * The feature id for the '<em><b>Color Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__COLOR_TEXTO = 2;

  /**
   * The feature id for the '<em><b>Size Fuente H1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__SIZE_FUENTE_H1 = 3;

  /**
   * The feature id for the '<em><b>Size Fuente H2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__SIZE_FUENTE_H2 = 4;

  /**
   * The feature id for the '<em><b>Size Fuente Cuerpo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA__SIZE_FUENTE_CUERPO = 5;

  /**
   * The number of structural features of the '<em>Apariencia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APARIENCIA_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl <em>Pagina</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getPagina()
   * @generated
   */
  int PAGINA = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGINA__NAME = 0;

  /**
   * The feature id for the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGINA__TITULO = 1;

  /**
   * The feature id for the '<em><b>Cuerpo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGINA__CUERPO = 2;

  /**
   * The number of structural features of the '<em>Pagina</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGINA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.CuerpoImpl <em>Cuerpo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.CuerpoImpl
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getCuerpo()
   * @generated
   */
  int CUERPO = 3;

  /**
   * The feature id for the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUERPO__TEXTO = 0;

  /**
   * The feature id for the '<em><b>Productos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUERPO__PRODUCTOS = 1;

  /**
   * The number of structural features of the '<em>Cuerpo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUERPO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.ProductoImpl <em>Producto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ProductoImpl
   * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getProducto()
   * @generated
   */
  int PRODUCTO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Precio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__PRECIO = 2;

  /**
   * The feature id for the '<em><b>Imagen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__IMAGEN = 3;

  /**
   * The feature id for the '<em><b>Conreceta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__CONRECETA = 4;

  /**
   * The feature id for the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO__DESCRIPCION = 5;

  /**
   * The number of structural features of the '<em>Producto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTO_FEATURE_COUNT = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia <em>Parafarmacia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parafarmacia</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia
   * @generated
   */
  EClass getParafarmacia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getTitulo <em>Titulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titulo</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getTitulo()
   * @see #getParafarmacia()
   * @generated
   */
  EAttribute getParafarmacia_Titulo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getDescripcion <em>Descripcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Descripcion</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getDescripcion()
   * @see #getParafarmacia()
   * @generated
   */
  EAttribute getParafarmacia_Descripcion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getApariencia <em>Apariencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Apariencia</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getApariencia()
   * @see #getParafarmacia()
   * @generated
   */
  EReference getParafarmacia_Apariencia();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getPaginas <em>Paginas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paginas</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getPaginas()
   * @see #getParafarmacia()
   * @generated
   */
  EReference getParafarmacia_Paginas();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia <em>Apariencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Apariencia</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia
   * @generated
   */
  EClass getApariencia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorFondo1 <em>Color Fondo1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color Fondo1</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorFondo1()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_ColorFondo1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorFondo2 <em>Color Fondo2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color Fondo2</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorFondo2()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_ColorFondo2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorTexto <em>Color Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color Texto</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getColorTexto()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_ColorTexto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteH1 <em>Size Fuente H1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size Fuente H1</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteH1()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_SizeFuenteH1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteH2 <em>Size Fuente H2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size Fuente H2</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteH2()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_SizeFuenteH2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteCuerpo <em>Size Fuente Cuerpo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size Fuente Cuerpo</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Apariencia#getSizeFuenteCuerpo()
   * @see #getApariencia()
   * @generated
   */
  EAttribute getApariencia_SizeFuenteCuerpo();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina <em>Pagina</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pagina</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Pagina
   * @generated
   */
  EClass getPagina();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getName()
   * @see #getPagina()
   * @generated
   */
  EAttribute getPagina_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getTitulo <em>Titulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Titulo</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getTitulo()
   * @see #getPagina()
   * @generated
   */
  EAttribute getPagina_Titulo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getCuerpo <em>Cuerpo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cuerpo</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Pagina#getCuerpo()
   * @see #getPagina()
   * @generated
   */
  EReference getPagina_Cuerpo();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo <em>Cuerpo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cuerpo</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo
   * @generated
   */
  EClass getCuerpo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo#getTexto <em>Texto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texto</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo#getTexto()
   * @see #getCuerpo()
   * @generated
   */
  EAttribute getCuerpo_Texto();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo#getProductos <em>Productos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Productos</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Cuerpo#getProductos()
   * @see #getCuerpo()
   * @generated
   */
  EReference getCuerpo_Productos();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto <em>Producto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Producto</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto
   * @generated
   */
  EClass getProducto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#getName()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#getNombre()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getPrecio <em>Precio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Precio</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#getPrecio()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Precio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getImagen <em>Imagen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imagen</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#getImagen()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Imagen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#isConreceta <em>Conreceta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Conreceta</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#isConreceta()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Conreceta();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getDescripcion <em>Descripcion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Descripcion</em>'.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.Producto#getDescripcion()
   * @see #getProducto()
   * @generated
   */
  EAttribute getProducto_Descripcion();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ParafarmaciaFactory getParafarmaciaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaImpl <em>Parafarmacia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaImpl
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getParafarmacia()
     * @generated
     */
    EClass PARAFARMACIA = eINSTANCE.getParafarmacia();

    /**
     * The meta object literal for the '<em><b>Titulo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAFARMACIA__TITULO = eINSTANCE.getParafarmacia_Titulo();

    /**
     * The meta object literal for the '<em><b>Descripcion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAFARMACIA__DESCRIPCION = eINSTANCE.getParafarmacia_Descripcion();

    /**
     * The meta object literal for the '<em><b>Apariencia</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAFARMACIA__APARIENCIA = eINSTANCE.getParafarmacia_Apariencia();

    /**
     * The meta object literal for the '<em><b>Paginas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAFARMACIA__PAGINAS = eINSTANCE.getParafarmacia_Paginas();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl <em>Apariencia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.AparienciaImpl
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getApariencia()
     * @generated
     */
    EClass APARIENCIA = eINSTANCE.getApariencia();

    /**
     * The meta object literal for the '<em><b>Color Fondo1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__COLOR_FONDO1 = eINSTANCE.getApariencia_ColorFondo1();

    /**
     * The meta object literal for the '<em><b>Color Fondo2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__COLOR_FONDO2 = eINSTANCE.getApariencia_ColorFondo2();

    /**
     * The meta object literal for the '<em><b>Color Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__COLOR_TEXTO = eINSTANCE.getApariencia_ColorTexto();

    /**
     * The meta object literal for the '<em><b>Size Fuente H1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__SIZE_FUENTE_H1 = eINSTANCE.getApariencia_SizeFuenteH1();

    /**
     * The meta object literal for the '<em><b>Size Fuente H2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__SIZE_FUENTE_H2 = eINSTANCE.getApariencia_SizeFuenteH2();

    /**
     * The meta object literal for the '<em><b>Size Fuente Cuerpo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute APARIENCIA__SIZE_FUENTE_CUERPO = eINSTANCE.getApariencia_SizeFuenteCuerpo();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl <em>Pagina</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.PaginaImpl
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getPagina()
     * @generated
     */
    EClass PAGINA = eINSTANCE.getPagina();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGINA__NAME = eINSTANCE.getPagina_Name();

    /**
     * The meta object literal for the '<em><b>Titulo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGINA__TITULO = eINSTANCE.getPagina_Titulo();

    /**
     * The meta object literal for the '<em><b>Cuerpo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGINA__CUERPO = eINSTANCE.getPagina_Cuerpo();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.CuerpoImpl <em>Cuerpo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.CuerpoImpl
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getCuerpo()
     * @generated
     */
    EClass CUERPO = eINSTANCE.getCuerpo();

    /**
     * The meta object literal for the '<em><b>Texto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUERPO__TEXTO = eINSTANCE.getCuerpo_Texto();

    /**
     * The meta object literal for the '<em><b>Productos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUERPO__PRODUCTOS = eINSTANCE.getCuerpo_Productos();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.parafarmacia.parafarmacia.impl.ProductoImpl <em>Producto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ProductoImpl
     * @see org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaPackageImpl#getProducto()
     * @generated
     */
    EClass PRODUCTO = eINSTANCE.getProducto();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__NAME = eINSTANCE.getProducto_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__NOMBRE = eINSTANCE.getProducto_Nombre();

    /**
     * The meta object literal for the '<em><b>Precio</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__PRECIO = eINSTANCE.getProducto_Precio();

    /**
     * The meta object literal for the '<em><b>Imagen</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__IMAGEN = eINSTANCE.getProducto_Imagen();

    /**
     * The meta object literal for the '<em><b>Conreceta</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__CONRECETA = eINSTANCE.getProducto_Conreceta();

    /**
     * The meta object literal for the '<em><b>Descripcion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRODUCTO__DESCRIPCION = eINSTANCE.getProducto_Descripcion();

  }

} //ParafarmaciaPackage
