/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parafarmacia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getDescripcion <em>Descripcion</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getApariencia <em>Apariencia</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getPaginas <em>Paginas</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getParafarmacia()
 * @model
 * @generated
 */
public interface Parafarmacia extends EObject
{
  /**
   * Returns the value of the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titulo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titulo</em>' attribute.
   * @see #setTitulo(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getParafarmacia_Titulo()
   * @model
   * @generated
   */
  String getTitulo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getTitulo <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titulo</em>' attribute.
   * @see #getTitulo()
   * @generated
   */
  void setTitulo(String value);

  /**
   * Returns the value of the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Descripcion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descripcion</em>' attribute.
   * @see #setDescripcion(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getParafarmacia_Descripcion()
   * @model
   * @generated
   */
  String getDescripcion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getDescripcion <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descripcion</em>' attribute.
   * @see #getDescripcion()
   * @generated
   */
  void setDescripcion(String value);

  /**
   * Returns the value of the '<em><b>Apariencia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Apariencia</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apariencia</em>' containment reference.
   * @see #setApariencia(Apariencia)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getParafarmacia_Apariencia()
   * @model containment="true"
   * @generated
   */
  Apariencia getApariencia();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia#getApariencia <em>Apariencia</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apariencia</em>' containment reference.
   * @see #getApariencia()
   * @generated
   */
  void setApariencia(Apariencia value);

  /**
   * Returns the value of the '<em><b>Paginas</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.parafarmacia.parafarmacia.Pagina}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paginas</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paginas</em>' containment reference list.
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getParafarmacia_Paginas()
   * @model containment="true"
   * @generated
   */
  EList<Pagina> getPaginas();

} // Parafarmacia
