/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage
 * @generated
 */
public interface ParafarmaciaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ParafarmaciaFactory eINSTANCE = org.xtext.dsl.parafarmacia.parafarmacia.impl.ParafarmaciaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Parafarmacia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parafarmacia</em>'.
   * @generated
   */
  Parafarmacia createParafarmacia();

  /**
   * Returns a new object of class '<em>Apariencia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Apariencia</em>'.
   * @generated
   */
  Apariencia createApariencia();

  /**
   * Returns a new object of class '<em>Pagina</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pagina</em>'.
   * @generated
   */
  Pagina createPagina();

  /**
   * Returns a new object of class '<em>Cuerpo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cuerpo</em>'.
   * @generated
   */
  Cuerpo createCuerpo();

  /**
   * Returns a new object of class '<em>Producto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Producto</em>'.
   * @generated
   */
  Producto createProducto();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ParafarmaciaPackage getParafarmaciaPackage();

} //ParafarmaciaFactory
