/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.parafarmacia;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Producto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getPrecio <em>Precio</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getImagen <em>Imagen</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#isConreceta <em>Conreceta</em>}</li>
 *   <li>{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getDescripcion <em>Descripcion</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto()
 * @model
 * @generated
 */
public interface Producto extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Precio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precio</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precio</em>' attribute.
   * @see #setPrecio(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Precio()
   * @model
   * @generated
   */
  String getPrecio();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getPrecio <em>Precio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precio</em>' attribute.
   * @see #getPrecio()
   * @generated
   */
  void setPrecio(String value);

  /**
   * Returns the value of the '<em><b>Imagen</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imagen</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imagen</em>' attribute.
   * @see #setImagen(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Imagen()
   * @model
   * @generated
   */
  String getImagen();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getImagen <em>Imagen</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imagen</em>' attribute.
   * @see #getImagen()
   * @generated
   */
  void setImagen(String value);

  /**
   * Returns the value of the '<em><b>Conreceta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conreceta</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conreceta</em>' attribute.
   * @see #setConreceta(boolean)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Conreceta()
   * @model
   * @generated
   */
  boolean isConreceta();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#isConreceta <em>Conreceta</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conreceta</em>' attribute.
   * @see #isConreceta()
   * @generated
   */
  void setConreceta(boolean value);

  /**
   * Returns the value of the '<em><b>Descripcion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Descripcion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descripcion</em>' attribute.
   * @see #setDescripcion(String)
   * @see org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage#getProducto_Descripcion()
   * @model
   * @generated
   */
  String getDescripcion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.parafarmacia.parafarmacia.Producto#getDescripcion <em>Descripcion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descripcion</em>' attribute.
   * @see #getDescripcion()
   * @generated
   */
  void setDescripcion(String value);

} // Producto
