/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.validation

import org.eclipse.xtext.validation.Check
import org.xtext.dsl.parafarmacia.parafarmacia.ParafarmaciaPackage
import org.xtext.dsl.parafarmacia.parafarmacia.Apariencia

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ParafarmaciaValidator extends AbstractParafarmaciaValidator {
	
	public static val INVALID_COLOR = 'invalidColor'
	public static val INVALID_SIZE_TEXT = 'invalidSizeText'

	@Check
	def checkFormatColor(Apariencia apariencia) {
		if (apariencia.getColorFondo1().length > 7 || apariencia.colorFondo1.length < 3) {
			error('El color no puede tener más de 7 caracteres ni menos de 3', 
					ParafarmaciaPackage.Literals.APARIENCIA__COLOR_FONDO1,
					INVALID_COLOR)
		}
		if (apariencia.getColorFondo2().length > 7 || apariencia.colorFondo2.length < 3) {
			error('El color no puede tener más de 7 caracteres ni menos de 3', 
					ParafarmaciaPackage.Literals.APARIENCIA__COLOR_FONDO2,
					INVALID_COLOR)
		}
		if (apariencia.getColorTexto().length > 7 || apariencia.colorTexto.length < 3) {
			error('El color no puede tener más de 7 caracteres ni menos de 3', 
					ParafarmaciaPackage.Literals.APARIENCIA__COLOR_TEXTO,
					INVALID_COLOR)
		}
	}
	
	@Check
	def checkSizeTextr(Apariencia apariencia) {
		if (apariencia.sizeFuenteH1 > 100 || apariencia.sizeFuenteH1 < 2) {
			error('El tamaño de texto no puede ser mayor que 100 ni menor que 2', 
					ParafarmaciaPackage.Literals.APARIENCIA__SIZE_FUENTE_H1,
					INVALID_SIZE_TEXT)
		}
		if (apariencia.sizeFuenteH2 > 100 || apariencia.sizeFuenteH2 < 2) {
			error('El tamaño de texto no puede ser mayor que 100 ni menor que 2', 
					ParafarmaciaPackage.Literals.APARIENCIA__SIZE_FUENTE_H2,
					INVALID_SIZE_TEXT)
		}
		if (apariencia.sizeFuenteCuerpo > 100 || apariencia.sizeFuenteCuerpo < 2) {
			error('El tamaño de texto del cuerpo no puede ser mayor que 100 ni menor que 2', 
					ParafarmaciaPackage.Literals.APARIENCIA__SIZE_FUENTE_CUERPO,
					INVALID_SIZE_TEXT)
		}
	}
	
}
