/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Apariencia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getPrincipal <em>Principal</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getPrincipalClaro <em>Principal Claro</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getSecundario <em>Secundario</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getFondo <em>Fondo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getFondoProductos <em>Fondo Productos</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getPrecios <em>Precios</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getTexto <em>Texto</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getTituloColor <em>Titulo Color</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getNormal <em>Normal</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getGrande <em>Grande</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getMenu <em>Menu</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Apariencia#getLateral <em>Lateral</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia()
 * @model
 * @generated
 */
public interface Apariencia extends EObject
{
  /**
   * Returns the value of the '<em><b>Principal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Principal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Principal</em>' attribute.
   * @see #setPrincipal(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Principal()
   * @model
   * @generated
   */
  String getPrincipal();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getPrincipal <em>Principal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Principal</em>' attribute.
   * @see #getPrincipal()
   * @generated
   */
  void setPrincipal(String value);

  /**
   * Returns the value of the '<em><b>Principal Claro</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Principal Claro</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Principal Claro</em>' attribute.
   * @see #setPrincipalClaro(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_PrincipalClaro()
   * @model
   * @generated
   */
  String getPrincipalClaro();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getPrincipalClaro <em>Principal Claro</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Principal Claro</em>' attribute.
   * @see #getPrincipalClaro()
   * @generated
   */
  void setPrincipalClaro(String value);

  /**
   * Returns the value of the '<em><b>Secundario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Secundario</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secundario</em>' attribute.
   * @see #setSecundario(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Secundario()
   * @model
   * @generated
   */
  String getSecundario();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getSecundario <em>Secundario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secundario</em>' attribute.
   * @see #getSecundario()
   * @generated
   */
  void setSecundario(String value);

  /**
   * Returns the value of the '<em><b>Fondo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fondo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fondo</em>' attribute.
   * @see #setFondo(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Fondo()
   * @model
   * @generated
   */
  String getFondo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getFondo <em>Fondo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fondo</em>' attribute.
   * @see #getFondo()
   * @generated
   */
  void setFondo(String value);

  /**
   * Returns the value of the '<em><b>Fondo Productos</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fondo Productos</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fondo Productos</em>' attribute.
   * @see #setFondoProductos(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_FondoProductos()
   * @model
   * @generated
   */
  String getFondoProductos();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getFondoProductos <em>Fondo Productos</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fondo Productos</em>' attribute.
   * @see #getFondoProductos()
   * @generated
   */
  void setFondoProductos(String value);

  /**
   * Returns the value of the '<em><b>Precios</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Precios</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precios</em>' attribute.
   * @see #setPrecios(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Precios()
   * @model
   * @generated
   */
  String getPrecios();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getPrecios <em>Precios</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precios</em>' attribute.
   * @see #getPrecios()
   * @generated
   */
  void setPrecios(String value);

  /**
   * Returns the value of the '<em><b>Texto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Texto</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texto</em>' attribute.
   * @see #setTexto(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Texto()
   * @model
   * @generated
   */
  String getTexto();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getTexto <em>Texto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texto</em>' attribute.
   * @see #getTexto()
   * @generated
   */
  void setTexto(String value);

  /**
   * Returns the value of the '<em><b>Titulo Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titulo Color</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titulo Color</em>' attribute.
   * @see #setTituloColor(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_TituloColor()
   * @model
   * @generated
   */
  String getTituloColor();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getTituloColor <em>Titulo Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titulo Color</em>' attribute.
   * @see #getTituloColor()
   * @generated
   */
  void setTituloColor(String value);

  /**
   * Returns the value of the '<em><b>Normal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Normal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Normal</em>' attribute.
   * @see #setNormal(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Normal()
   * @model
   * @generated
   */
  String getNormal();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getNormal <em>Normal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Normal</em>' attribute.
   * @see #getNormal()
   * @generated
   */
  void setNormal(String value);

  /**
   * Returns the value of the '<em><b>Grande</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Grande</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grande</em>' attribute.
   * @see #setGrande(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Grande()
   * @model
   * @generated
   */
  String getGrande();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getGrande <em>Grande</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grande</em>' attribute.
   * @see #getGrande()
   * @generated
   */
  void setGrande(String value);

  /**
   * Returns the value of the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titulo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titulo</em>' attribute.
   * @see #setTitulo(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Titulo()
   * @model
   * @generated
   */
  String getTitulo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getTitulo <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titulo</em>' attribute.
   * @see #getTitulo()
   * @generated
   */
  void setTitulo(String value);

  /**
   * Returns the value of the '<em><b>Menu</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Menu</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Menu</em>' attribute.
   * @see #setMenu(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Menu()
   * @model
   * @generated
   */
  String getMenu();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getMenu <em>Menu</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Menu</em>' attribute.
   * @see #getMenu()
   * @generated
   */
  void setMenu(String value);

  /**
   * Returns the value of the '<em><b>Lateral</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lateral</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lateral</em>' attribute.
   * @see #setLateral(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getApariencia_Lateral()
   * @model
   * @generated
   */
  String getLateral();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Apariencia#getLateral <em>Lateral</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lateral</em>' attribute.
   * @see #getLateral()
   * @generated
   */
  void setLateral(String value);

} // Apariencia
