/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Direccion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.Direccion#getCalle <em>Calle</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Direccion#getCiudad <em>Ciudad</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Direccion#getPais <em>Pais</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.generador.generador.GeneradorPackage#getDireccion()
 * @model
 * @generated
 */
public interface Direccion extends EObject
{
  /**
   * Returns the value of the '<em><b>Calle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Calle</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Calle</em>' attribute.
   * @see #setCalle(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getDireccion_Calle()
   * @model
   * @generated
   */
  String getCalle();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Direccion#getCalle <em>Calle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Calle</em>' attribute.
   * @see #getCalle()
   * @generated
   */
  void setCalle(String value);

  /**
   * Returns the value of the '<em><b>Ciudad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ciudad</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ciudad</em>' attribute.
   * @see #setCiudad(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getDireccion_Ciudad()
   * @model
   * @generated
   */
  String getCiudad();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Direccion#getCiudad <em>Ciudad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ciudad</em>' attribute.
   * @see #getCiudad()
   * @generated
   */
  void setCiudad(String value);

  /**
   * Returns the value of the '<em><b>Pais</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pais</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pais</em>' attribute.
   * @see #setPais(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getDireccion_Pais()
   * @model
   * @generated
   */
  String getPais();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Direccion#getPais <em>Pais</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pais</em>' attribute.
   * @see #getPais()
   * @generated
   */
  void setPais(String value);

} // Direccion
