/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parafarmacia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getTitulo <em>Titulo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getFuente <em>Fuente</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getNombre <em>Nombre</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getDireccion <em>Direccion</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getCif <em>Cif</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getRegistro <em>Registro</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getCorreo <em>Correo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getTelefono <em>Telefono</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getTipo <em>Tipo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getApariencia <em>Apariencia</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getCategorias <em>Categorias</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getNumProductosPorFila <em>Num Productos Por Fila</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getProductos <em>Productos</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getNombreUsuario <em>Nombre Usuario</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getEmail <em>Email</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Parafarmacia#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia()
 * @model
 * @generated
 */
public interface Parafarmacia extends EObject
{
  /**
   * Returns the value of the '<em><b>Titulo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titulo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Titulo</em>' attribute.
   * @see #setTitulo(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Titulo()
   * @model
   * @generated
   */
  String getTitulo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getTitulo <em>Titulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Titulo</em>' attribute.
   * @see #getTitulo()
   * @generated
   */
  void setTitulo(String value);

  /**
   * Returns the value of the '<em><b>Fuente</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fuente</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fuente</em>' attribute.
   * @see #setFuente(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Fuente()
   * @model
   * @generated
   */
  String getFuente();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getFuente <em>Fuente</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fuente</em>' attribute.
   * @see #getFuente()
   * @generated
   */
  void setFuente(String value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' attribute.
   * @see #setNombre(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Nombre()
   * @model
   * @generated
   */
  String getNombre();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getNombre <em>Nombre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' attribute.
   * @see #getNombre()
   * @generated
   */
  void setNombre(String value);

  /**
   * Returns the value of the '<em><b>Direccion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direccion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direccion</em>' containment reference.
   * @see #setDireccion(Direccion)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Direccion()
   * @model containment="true"
   * @generated
   */
  Direccion getDireccion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getDireccion <em>Direccion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direccion</em>' containment reference.
   * @see #getDireccion()
   * @generated
   */
  void setDireccion(Direccion value);

  /**
   * Returns the value of the '<em><b>Cif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cif</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cif</em>' attribute.
   * @see #setCif(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Cif()
   * @model
   * @generated
   */
  String getCif();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getCif <em>Cif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cif</em>' attribute.
   * @see #getCif()
   * @generated
   */
  void setCif(String value);

  /**
   * Returns the value of the '<em><b>Registro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Registro</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Registro</em>' containment reference.
   * @see #setRegistro(Registro)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Registro()
   * @model containment="true"
   * @generated
   */
  Registro getRegistro();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getRegistro <em>Registro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Registro</em>' containment reference.
   * @see #getRegistro()
   * @generated
   */
  void setRegistro(Registro value);

  /**
   * Returns the value of the '<em><b>Correo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Correo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Correo</em>' attribute.
   * @see #setCorreo(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Correo()
   * @model
   * @generated
   */
  String getCorreo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getCorreo <em>Correo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Correo</em>' attribute.
   * @see #getCorreo()
   * @generated
   */
  void setCorreo(String value);

  /**
   * Returns the value of the '<em><b>Telefono</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Telefono</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Telefono</em>' attribute.
   * @see #setTelefono(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Telefono()
   * @model
   * @generated
   */
  int getTelefono();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getTelefono <em>Telefono</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Telefono</em>' attribute.
   * @see #getTelefono()
   * @generated
   */
  void setTelefono(int value);

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' containment reference.
   * @see #setTipo(Tipo)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Tipo()
   * @model containment="true"
   * @generated
   */
  Tipo getTipo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getTipo <em>Tipo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' containment reference.
   * @see #getTipo()
   * @generated
   */
  void setTipo(Tipo value);

  /**
   * Returns the value of the '<em><b>Apariencia</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Apariencia</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Apariencia</em>' containment reference.
   * @see #setApariencia(Apariencia)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Apariencia()
   * @model containment="true"
   * @generated
   */
  Apariencia getApariencia();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getApariencia <em>Apariencia</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Apariencia</em>' containment reference.
   * @see #getApariencia()
   * @generated
   */
  void setApariencia(Apariencia value);

  /**
   * Returns the value of the '<em><b>Categorias</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Categorias</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Categorias</em>' attribute list.
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Categorias()
   * @model unique="false"
   * @generated
   */
  EList<String> getCategorias();

  /**
   * Returns the value of the '<em><b>Num Productos Por Fila</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num Productos Por Fila</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Productos Por Fila</em>' attribute.
   * @see #setNumProductosPorFila(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_NumProductosPorFila()
   * @model
   * @generated
   */
  int getNumProductosPorFila();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getNumProductosPorFila <em>Num Productos Por Fila</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Productos Por Fila</em>' attribute.
   * @see #getNumProductosPorFila()
   * @generated
   */
  void setNumProductosPorFila(int value);

  /**
   * Returns the value of the '<em><b>Productos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.generador.generador.Producto}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Productos</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Productos</em>' containment reference list.
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Productos()
   * @model containment="true"
   * @generated
   */
  EList<Producto> getProductos();

  /**
   * Returns the value of the '<em><b>Nombre Usuario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nombre Usuario</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre Usuario</em>' attribute.
   * @see #setNombreUsuario(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_NombreUsuario()
   * @model
   * @generated
   */
  String getNombreUsuario();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getNombreUsuario <em>Nombre Usuario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre Usuario</em>' attribute.
   * @see #getNombreUsuario()
   * @generated
   */
  void setNombreUsuario(String value);

  /**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Email</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Password</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getParafarmacia_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Parafarmacia#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

} // Parafarmacia
