/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.generador.generador;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Registro</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.generador.generador.Registro#getTomo <em>Tomo</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Registro#getFolio <em>Folio</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Registro#getSeccion <em>Seccion</em>}</li>
 *   <li>{@link org.xtext.dsl.generador.generador.Registro#getHoja <em>Hoja</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.generador.generador.GeneradorPackage#getRegistro()
 * @model
 * @generated
 */
public interface Registro extends EObject
{
  /**
   * Returns the value of the '<em><b>Tomo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tomo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tomo</em>' attribute.
   * @see #setTomo(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getRegistro_Tomo()
   * @model
   * @generated
   */
  int getTomo();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Registro#getTomo <em>Tomo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tomo</em>' attribute.
   * @see #getTomo()
   * @generated
   */
  void setTomo(int value);

  /**
   * Returns the value of the '<em><b>Folio</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Folio</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folio</em>' attribute.
   * @see #setFolio(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getRegistro_Folio()
   * @model
   * @generated
   */
  int getFolio();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Registro#getFolio <em>Folio</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Folio</em>' attribute.
   * @see #getFolio()
   * @generated
   */
  void setFolio(int value);

  /**
   * Returns the value of the '<em><b>Seccion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seccion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seccion</em>' attribute.
   * @see #setSeccion(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getRegistro_Seccion()
   * @model
   * @generated
   */
  int getSeccion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Registro#getSeccion <em>Seccion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seccion</em>' attribute.
   * @see #getSeccion()
   * @generated
   */
  void setSeccion(int value);

  /**
   * Returns the value of the '<em><b>Hoja</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hoja</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hoja</em>' attribute.
   * @see #setHoja(int)
   * @see org.xtext.dsl.generador.generador.GeneradorPackage#getRegistro_Hoja()
   * @model
   * @generated
   */
  int getHoja();

  /**
   * Sets the value of the '{@link org.xtext.dsl.generador.generador.Registro#getHoja <em>Hoja</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hoja</em>' attribute.
   * @see #getHoja()
   * @generated
   */
  void setHoja(int value);

} // Registro
