/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractParafarmaciaScopeProvider extends DelegatingScopeProvider {
}
