/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.dsl.parafarmacia.ui.internal.ParafarmaciaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ParafarmaciaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ParafarmaciaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ParafarmaciaActivator.getInstance().getInjector(ParafarmaciaActivator.ORG_XTEXT_DSL_PARAFARMACIA_PARAFARMACIA);
	}
	
}
