/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ide


/**
 * Use this class to register ide components.
 */
class ParafarmaciaIdeModule extends AbstractParafarmaciaIdeModule {
}
