/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.dsl.parafarmacia.ParafarmaciaRuntimeModule;
import org.xtext.dsl.parafarmacia.ParafarmaciaStandaloneSetup;
import org.xtext.dsl.parafarmacia.ide.ParafarmaciaIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ParafarmaciaIdeSetup extends ParafarmaciaStandaloneSetup {
  @Override
  public Injector createInjector() {
    ParafarmaciaRuntimeModule _parafarmaciaRuntimeModule = new ParafarmaciaRuntimeModule();
    ParafarmaciaIdeModule _parafarmaciaIdeModule = new ParafarmaciaIdeModule();
    return Guice.createInjector(Modules2.mixin(_parafarmaciaRuntimeModule, _parafarmaciaIdeModule));
  }
}
