/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ide;

import org.xtext.dsl.parafarmacia.ide.AbstractParafarmaciaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ParafarmaciaIdeModule extends AbstractParafarmaciaIdeModule {
}
