/*
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui.wizard;

import org.eclipse.xtext.ui.wizard.XtextNewProjectWizard;

import org.eclipse.xtext.ui.wizard.IExtendedProjectInfo;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import com.google.inject.Inject;

public class ParafarmaciaNewProjectWizard extends XtextNewProjectWizard {

	private ParafarmaciaWizardNewProjectCreationPage mainPage;

	@Inject
	public ParafarmaciaNewProjectWizard(IProjectCreator projectCreator) {
		super(projectCreator);
		setWindowTitle("New Parafarmacia Project");
	}

	protected ParafarmaciaWizardNewProjectCreationPage getMainPage() {
		return mainPage;
	}

	/**
	 * Use this method to add pages to the wizard.
	 * The one-time generated version of this class will add a default new project page to the wizard.
	 */
	@Override
	public void addPages() {
		mainPage = createMainPage("basicNewProjectPage");
		mainPage.setTitle("Parafarmacia Project");
		mainPage.setDescription("Create a new Parafarmacia project.");
		addPage(mainPage);
	}

	protected ParafarmaciaWizardNewProjectCreationPage createMainPage(String pageName) {
		return new ParafarmaciaWizardNewProjectCreationPage(pageName);
	}

	/**
	 * Use this method to read the project settings from the wizard pages and feed them into the project info class.
	 */
	@Override
	protected IExtendedProjectInfo getProjectInfo() {
		ParafarmaciaProjectInfo projectInfo = new ParafarmaciaProjectInfo();
		projectInfo.setProjectName(mainPage.getProjectName());
		if (!mainPage.useDefaults()) {
			projectInfo.setLocationPath(mainPage.getLocationPath());
		}
		return projectInfo;
	}

}
