/**
 * generated by Xtext 2.12.0
 */
package org.xtext.dsl.parafarmacia.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.jface.text.contentassist.ICompletionProposal;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.xtext.dsl.parafarmacia.parafarmacia.Parafarmacia;
import org.xtext.dsl.parafarmacia.ui.contentassist.AbstractParafarmaciaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ParafarmaciaProposalProvider extends AbstractParafarmaciaProposalProvider {
  @Override
  public void complete_Producto(final EObject o, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    ICompletionProposal propuesta = this.createCompletionProposal("Producto COD \"Nombre\" 20.20 descripcion \"Ejemplo de descripción.\";", context);
    acceptor.accept(propuesta);
  }
  
  public void completePagina_Name(final Parafarmacia i, final Assignment assignment, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    super.completePagina_Name(i, assignment, context, acceptor);
    String id = "Carrito";
    ICompletionProposal propuesta = this.createCompletionProposal(id, context);
    acceptor.accept(propuesta);
  }
}
